import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { invoices, retainerPeriods, emailSends } from "@/lib/db/schema";
import { requireOrg } from "@/lib/auth/session";
import { requireAdmin } from "@/lib/auth/permissions";
import { eq, and, ne, desc, lte, gte, inArray, sql } from "drizzle-orm";
import {
  generateInvoice,
  groupEntriesByProjectTask,
  fetchBillableEntries,
} from "@/lib/invoices/generate";
import {
  generateLineItemSummaries,
  isAISummaryAvailable,
} from "@/lib/invoices/summarize";

type RouteParams = {
  params: Promise<{ orgId: string }>;
};

// GET /api/v1/organizations/[orgId]/invoices
export async function GET(request: NextRequest, { params }: RouteParams) {
  try {
    const { orgId } = await params;
    const { organization, membership } = await requireOrg();

    if (organization.id !== orgId) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    requireAdmin(membership.role);

    const { searchParams } = new URL(request.url);
    const includeVoided = searchParams.get("includeVoided") === "true";

    const invoiceList = await db.query.invoices.findMany({
      where: includeVoided
        ? eq(invoices.organizationId, orgId)
        : and(eq(invoices.organizationId, orgId), ne(invoices.status, "voided")),
      with: {
        client: {
          columns: { id: true, name: true, color: true },
        },
        lineItems: true,
      },
      orderBy: [desc(invoices.createdAt)],
    });

    // Fetch email delivery status for sent invoices
    const sentInvoiceIds = invoiceList
      .filter((inv) => inv.status === "sent" || inv.status === "viewed")
      .map((inv) => inv.id);

    const deliveryStatusMap = new Map<string, string>();
    if (sentInvoiceIds.length > 0) {
      const sends = await db
        .select({
          entityId: emailSends.entityId,
          status: emailSends.status,
        })
        .from(emailSends)
        .where(
          and(
            eq(emailSends.entityType, "invoice"),
            inArray(emailSends.entityId, sentInvoiceIds)
          )
        );
      for (const send of sends) {
        deliveryStatusMap.set(send.entityId, send.status);
      }
    }

    return NextResponse.json({
      invoices: invoiceList.map((inv) => ({
        id: inv.id,
        invoiceNumber: inv.invoiceNumber,
        status: inv.status,
        isAutoGenerated: inv.isAutoGenerated,
        dueDate: inv.dueDate,
        periodStart: inv.periodStart,
        periodEnd: inv.periodEnd,
        subtotal: inv.subtotal,
        totalMinutes: inv.totalMinutes,
        createdAt: inv.createdAt.toISOString(),
        sentAt: inv.sentAt?.toISOString() || null,
        viewedAt: inv.viewedAt?.toISOString() || null,
        publicToken: inv.publicToken,
        client: inv.client,
        lineItemCount: inv.lineItems.length,
        emailDeliveryStatus: deliveryStatusMap.get(inv.id) || null,
      })),
      aiSummaryAvailable: isAISummaryAvailable(),
    });
  } catch (error) {
    if (error instanceof Error && error.message === "Unauthorized") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    if (error instanceof Error && error.message === "Forbidden") {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }
    if (error instanceof Error && error.message === "No organization found") {
      return NextResponse.json(
        { error: "No organization found" },
        { status: 404 }
      );
    }
    console.error("Error fetching invoices:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

// POST /api/v1/organizations/[orgId]/invoices
export async function POST(request: NextRequest, { params }: RouteParams) {
  try {
    const { orgId } = await params;
    const { organization, membership } = await requireOrg();

    if (organization.id !== orgId) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    requireAdmin(membership.role);

    const body = await request.json();
    const { clientId, from, to, includeSummaries = false, force = false, deleteOverlapping = false } = body;

    // Validate required fields
    if (!clientId) {
      return NextResponse.json(
        { error: "clientId is required" },
        { status: 400 }
      );
    }

    if (!from || !to) {
      return NextResponse.json(
        { error: "Both 'from' and 'to' dates are required" },
        { status: 400 }
      );
    }

    // Validate date format
    const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
    if (!dateRegex.test(from) || !dateRegex.test(to)) {
      return NextResponse.json(
        { error: "Dates must be in YYYY-MM-DD format" },
        { status: 400 }
      );
    }

    // Check for overlapping draft invoices
    if (!force) {
      const overlapping = await db.query.invoices.findMany({
        where: and(
          eq(invoices.organizationId, orgId),
          eq(invoices.clientId, clientId),
          eq(invoices.status, "draft"),
          lte(invoices.periodStart, to),
          gte(invoices.periodEnd, from)
        ),
        with: {
          client: { columns: { id: true, name: true, color: true } },
        },
      });

      if (overlapping.length > 0) {
        if (deleteOverlapping) {
          // Delete overlapping drafts before generating
          await db
            .delete(invoices)
            .where(inArray(invoices.id, overlapping.map((inv) => inv.id)));
        } else {
          return NextResponse.json(
            {
              error: "Overlapping draft invoices found",
              overlapping: overlapping.map((inv) => ({
                id: inv.id,
                invoiceNumber: inv.invoiceNumber,
                periodStart: inv.periodStart,
                periodEnd: inv.periodEnd,
                subtotal: inv.subtotal,
                client: inv.client,
              })),
            },
            { status: 409 }
          );
        }
      }
    }

    // Generate invoice
    const result = await generateInvoice(orgId, clientId, from, to, {
      includeSummaries,
    });

    // Generate AI summaries if requested and available
    if (includeSummaries && isAISummaryAvailable()) {
      const entries = await fetchBillableEntries(orgId, clientId, from, to);
      const groups = groupEntriesByProjectTask(entries);
      const summaries = await generateLineItemSummaries(groups);

      // Update line items with AI summaries
      for (let i = 0; i < result.lineItems.length; i++) {
        if (summaries[i]) {
          await db
            .update(await import("@/lib/db/schema").then((m) => m.invoiceLineItems))
            .set({ description: summaries[i] })
            .where(
              eq(
                (await import("@/lib/db/schema")).invoiceLineItems.id,
                result.lineItems[i].id
              )
            );
          result.lineItems[i].description = summaries[i];
        }
      }
    }

    // Fetch client for response
    const client = await db.query.clients.findFirst({
      where: eq((await import("@/lib/db/schema")).clients.id, clientId),
    });

    return NextResponse.json(
      {
        invoice: {
          id: result.invoice.id,
          invoiceNumber: result.invoice.invoiceNumber,
          status: result.invoice.status,
          periodStart: result.invoice.periodStart,
          periodEnd: result.invoice.periodEnd,
          subtotal: result.invoice.subtotal,
          totalMinutes: result.invoice.totalMinutes,
          publicToken: result.invoice.publicToken,
          createdAt: result.invoice.createdAt.toISOString(),
          client: client
            ? { id: client.id, name: client.name, color: client.color }
            : null,
        },
        lineItems: result.lineItems.map((item) => ({
          id: item.id,
          projectName: item.projectName,
          taskName: item.taskName,
          description: item.description,
          minutes: item.minutes,
          rate: item.rate,
          amount: item.amount,
        })),
      },
      { status: 201 }
    );
  } catch (error) {
    if (error instanceof Error && error.message === "Unauthorized") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    if (error instanceof Error && error.message === "Forbidden") {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }
    if (error instanceof Error && error.message === "No organization found") {
      return NextResponse.json(
        { error: "No organization found" },
        { status: 404 }
      );
    }
    if (error instanceof Error) {
      // Handle known business errors
      if (
        error.message.includes("not found") ||
        error.message.includes("No billable entries")
      ) {
        return NextResponse.json({ error: error.message }, { status: 400 });
      }
    }
    console.error("Error creating invoice:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

// DELETE /api/v1/organizations/[orgId]/invoices (bulk)
export async function DELETE(request: NextRequest, { params }: RouteParams) {
  try {
    const { orgId } = await params;
    const { organization, membership } = await requireOrg();

    if (organization.id !== orgId) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    requireAdmin(membership.role);

    const body = await request.json();
    const { invoiceIds } = body as { invoiceIds: string[] };

    if (!invoiceIds || !Array.isArray(invoiceIds) || invoiceIds.length === 0) {
      return NextResponse.json(
        { error: "invoiceIds array is required" },
        { status: 400 }
      );
    }

    // Fetch all requested invoices
    const targetInvoices = await db.query.invoices.findMany({
      where: and(
        eq(invoices.organizationId, orgId),
        inArray(invoices.id, invoiceIds)
      ),
    });

    const drafts = targetInvoices.filter((inv) => inv.status === "draft");
    const nonDrafts = targetInvoices.filter(
      (inv) => inv.status !== "draft" && inv.status !== "voided"
    );

    let deleted = 0;
    let voided = 0;

    await db.transaction(async (tx) => {
      // Hard delete drafts
      if (drafts.length > 0) {
        await tx
          .delete(invoices)
          .where(inArray(invoices.id, drafts.map((inv) => inv.id)));
        deleted = drafts.length;
      }

      // Void non-drafts
      for (const inv of nonDrafts) {
        await tx
          .update(invoices)
          .set({ status: "voided", voidedAt: new Date() })
          .where(eq(invoices.id, inv.id));

        await tx
          .update(retainerPeriods)
          .set({ invoiceId: null, status: "active" })
          .where(eq(retainerPeriods.invoiceId, inv.id));

        voided++;
      }
    });

    return NextResponse.json({ success: true, deleted, voided });
  } catch (error) {
    if (error instanceof Error && error.message === "Unauthorized") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    if (error instanceof Error && error.message === "Forbidden") {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }
    if (error instanceof Error && error.message === "No organization found") {
      return NextResponse.json(
        { error: "No organization found" },
        { status: 404 }
      );
    }
    console.error("Error bulk deleting invoices:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
