import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { invoices } from "@/lib/db/schema";
import { requireOrg } from "@/lib/auth/session";
import { eq, desc } from "drizzle-orm";
import {
  generateInvoice,
  groupEntriesByProjectTask,
  fetchBillableEntries,
} from "@/lib/invoices/generate";
import {
  generateLineItemSummaries,
  isAISummaryAvailable,
} from "@/lib/invoices/summarize";

type RouteParams = {
  params: Promise<{ orgId: string }>;
};

// GET /api/v1/organizations/[orgId]/invoices
export async function GET(request: NextRequest, { params }: RouteParams) {
  try {
    const { orgId } = await params;
    const { organization } = await requireOrg();

    if (organization.id !== orgId) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const invoiceList = await db.query.invoices.findMany({
      where: eq(invoices.organizationId, orgId),
      with: {
        client: {
          columns: { id: true, name: true, color: true },
        },
        lineItems: true,
      },
      orderBy: [desc(invoices.createdAt)],
    });

    return NextResponse.json({
      invoices: invoiceList.map((inv) => ({
        id: inv.id,
        invoiceNumber: inv.invoiceNumber,
        status: inv.status,
        isAutoGenerated: inv.isAutoGenerated,
        dueDate: inv.dueDate,
        periodStart: inv.periodStart,
        periodEnd: inv.periodEnd,
        subtotal: inv.subtotal,
        totalMinutes: inv.totalMinutes,
        createdAt: inv.createdAt.toISOString(),
        sentAt: inv.sentAt?.toISOString() || null,
        viewedAt: inv.viewedAt?.toISOString() || null,
        publicToken: inv.publicToken,
        client: inv.client,
        lineItemCount: inv.lineItems.length,
      })),
      aiSummaryAvailable: isAISummaryAvailable(),
    });
  } catch (error) {
    if (error instanceof Error && error.message === "Unauthorized") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    if (error instanceof Error && error.message === "No organization found") {
      return NextResponse.json(
        { error: "No organization found" },
        { status: 404 }
      );
    }
    console.error("Error fetching invoices:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

// POST /api/v1/organizations/[orgId]/invoices
export async function POST(request: NextRequest, { params }: RouteParams) {
  try {
    const { orgId } = await params;
    const { organization } = await requireOrg();

    if (organization.id !== orgId) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const body = await request.json();
    const { clientId, from, to, includeSummaries = false } = body;

    // Validate required fields
    if (!clientId) {
      return NextResponse.json(
        { error: "clientId is required" },
        { status: 400 }
      );
    }

    if (!from || !to) {
      return NextResponse.json(
        { error: "Both 'from' and 'to' dates are required" },
        { status: 400 }
      );
    }

    // Validate date format
    const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
    if (!dateRegex.test(from) || !dateRegex.test(to)) {
      return NextResponse.json(
        { error: "Dates must be in YYYY-MM-DD format" },
        { status: 400 }
      );
    }

    // Generate invoice
    const result = await generateInvoice(orgId, clientId, from, to, {
      includeSummaries,
    });

    // Generate AI summaries if requested and available
    if (includeSummaries && isAISummaryAvailable()) {
      const entries = await fetchBillableEntries(orgId, clientId, from, to);
      const groups = groupEntriesByProjectTask(entries);
      const summaries = await generateLineItemSummaries(groups);

      // Update line items with AI summaries
      for (let i = 0; i < result.lineItems.length; i++) {
        if (summaries[i]) {
          await db
            .update(await import("@/lib/db/schema").then((m) => m.invoiceLineItems))
            .set({ description: summaries[i] })
            .where(
              eq(
                (await import("@/lib/db/schema")).invoiceLineItems.id,
                result.lineItems[i].id
              )
            );
          result.lineItems[i].description = summaries[i];
        }
      }
    }

    // Fetch client for response
    const client = await db.query.clients.findFirst({
      where: eq((await import("@/lib/db/schema")).clients.id, clientId),
    });

    return NextResponse.json(
      {
        invoice: {
          id: result.invoice.id,
          invoiceNumber: result.invoice.invoiceNumber,
          status: result.invoice.status,
          periodStart: result.invoice.periodStart,
          periodEnd: result.invoice.periodEnd,
          subtotal: result.invoice.subtotal,
          totalMinutes: result.invoice.totalMinutes,
          publicToken: result.invoice.publicToken,
          createdAt: result.invoice.createdAt.toISOString(),
          client: client
            ? { id: client.id, name: client.name, color: client.color }
            : null,
        },
        lineItems: result.lineItems.map((item) => ({
          id: item.id,
          projectName: item.projectName,
          taskName: item.taskName,
          description: item.description,
          minutes: item.minutes,
          rate: item.rate,
          amount: item.amount,
        })),
      },
      { status: 201 }
    );
  } catch (error) {
    if (error instanceof Error && error.message === "Unauthorized") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    if (error instanceof Error && error.message === "No organization found") {
      return NextResponse.json(
        { error: "No organization found" },
        { status: 404 }
      );
    }
    if (error instanceof Error) {
      // Handle known business errors
      if (
        error.message.includes("not found") ||
        error.message.includes("No billable entries")
      ) {
        return NextResponse.json({ error: error.message }, { status: 400 });
      }
    }
    console.error("Error creating invoice:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
