// Realistic events for the email preview and template tests.

import type { BusEvent } from "@/lib/bus/events";
import type { MailContext } from "./templates/context";

export const FIXTURE_CONTEXT: MailContext = {
  baseUrl: "https://vardo.example.com",
  instanceName: "node-a",
  orgName: "Joey Yax",
};

const timings = (ms: Partial<Record<"clone" | "build" | "pull" | "up" | "healthWait" | "cleanup", number>>) =>
  Object.fromEntries(
    Object.entries(ms).map(([phase, value]) => [
      phase,
      { startedAt: "2026-10-09T17:00:00.000Z", endedAt: "2026-10-09T17:00:00.000Z", ms: value },
    ]),
  );

export const EMAIL_FIXTURES: { name: string; event: BusEvent }[] = [
  {
    name: "deploy-success",
    event: {
      type: "deploy.success",
      title: "Deploy successful: acme-2026",
      message: "acme-2026 was deployed successfully in 1m 32s.",
      projectName: "acme-2026",
      appName: "acme-2026",
      project: "Acme Nonprofit",
      environment: "production",
      appId: "app_9xk2",
      deploymentId: "dep_a1b2",
      duration: "92s",
      durationMs: 92_400,
      domain: "acme.org",
      domains: ["acme.org", "www.acme.org"],
      gitSha: "a1b2c3d4e5f60718293a4b5c6d7e8f9012345678",
      gitMessage: "Fix donation form validation on mobile",
      gitAuthor: "Joey Yax",
      gitBranch: "main",
      repoUrl: "https://github.com/joeyyax/acme-2026",
      trigger: "webhook",
      slot: "green",
      previousSlot: "blue",
      stageTimings: timings({ clone: 3_200, build: 61_800, pull: 4_100, up: 6_300, healthWait: 12_400, cleanup: 2_100 }),
    },
  },
  {
    name: "deploy-failed",
    event: {
      type: "deploy.failed",
      title: "Deploy failed: search-data",
      message: "green slot did not become healthy: meilisearch crashed (crash-looping, 5 restarts). See logs above",
      projectName: "search-data",
      appName: "search-data",
      project: "Shop",
      environment: "production",
      appId: "app_s3ar",
      deploymentId: "dep_f41l",
      errorMessage: "green slot did not become healthy: meilisearch crashed (crash-looping, 5 restarts). See logs above",
      failedStage: "healthcheck",
      crashReason: "Error: Your database version (1.13.3) is incompatible with your current engine version (1.54.3).",
      trigger: "manual",
      triggeredBy: "Joey Yax",
      slot: "green",
      previousSlot: "blue",
      serving: "previous",
      durationMs: 74_000,
      stageTimings: timings({ pull: 8_200, up: 3_100, healthWait: 58_900 }),
      logTail: [
        "meilisearch-1  | 2026-10-09T17:02:11Z INFO  meilisearch: Starting Meilisearch",
        "meilisearch-1  | Error: Your database version (1.13.3) is incompatible with your current engine version (1.54.3).",
        "meilisearch-1  | To migrate data between Meilisearch versions, please follow our guide on https://www.meilisearch.com/docs/learn/update_and_migration/updating.",
        "meilisearch-1 exited with code 1 (restarting)",
        "meilisearch-1  | 2026-10-09T17:02:19Z INFO  meilisearch: Starting Meilisearch",
        "meilisearch-1  | Error: Your database version (1.13.3) is incompatible with your current engine version (1.54.3).",
        "meilisearch-1 exited with code 1 (restarting)",
      ],
    },
  },
  {
    name: "deploy-failed-build",
    event: {
      type: "deploy.failed",
      title: "Deploy failed: shop-staging",
      message: "Build failed: exit code 1",
      projectName: "Shop Staging",
      appName: "shop-staging",
      project: "Shop",
      environment: "staging",
      appId: "app_wh4s",
      deploymentId: "dep_b0rk",
      errorMessage: "Build failed: exit code 1",
      failedStage: "build",
      gitSha: "9f8e7d6c5b4a39281706f5e4d3c2b1a098765432",
      gitMessage: "Upgrade to PHP 8.4",
      gitAuthor: "Joey Yax",
      repoUrl: "https://github.com/joeyyax/wha",
      trigger: "webhook",
      serving: "previous",
      durationMs: 48_000,
      logTail: [
        "#12 [build 4/6] RUN composer install --no-dev --optimize-autoloader",
        "#12 1.204 Your requirements could not be resolved to an installable set of packages.",
        "#12 1.205   Problem 1",
        "#12 1.205     - Root composer.json requires php ~8.2.0 but your php version (8.4.1) does not satisfy that requirement.",
        "#12 ERROR: process \"/bin/sh -c composer install --no-dev --optimize-autoloader\" did not complete successfully: exit code: 2",
        "[deploy] ERROR: Build failed: exit code 1",
      ],
    },
  },
  {
    name: "deploy-incomplete",
    event: {
      type: "deploy.incomplete",
      title: "Post-deploy work unfinished: Formbricks",
      message: "Formbricks is deployed and serving, but the old slot (blue) is still running",
      projectName: "Formbricks",
      appName: "formbricks",
      project: "Tools",
      environment: "production",
      appId: "app_f0rm",
      deploymentId: "dep_1nc0",
      slot: "green",
      domains: ["forms.example.org"],
      reason:
        "the old slot (blue) is still running — Command failed: docker compose -f /opt/vardo/apps/formbricks/production/blue/docker-compose.yml -p formbricks-production-blue stop\nError response from daemon: cannot stop container: formbricks-production-blue-formbricks-1: tried to kill container, but did not receive an exit event",
    },
  },
  {
    name: "auto-rollback",
    event: {
      type: "deploy.rollback",
      title: "Auto-rollback: acme-2026",
      message: "Containers stopped within the grace period, so traffic went back to blue.",
      projectName: "acme-2026",
      appId: "app_9xk2",
      deploymentId: "dep_a1b2",
      rollbackSuccess: true,
      restoredSlot: "blue",
    },
  },
  {
    name: "backup-success",
    event: {
      type: "backup.success",
      title: "Backup successful: Nightly",
      message: "3 backup(s) completed",
      jobId: "job_n1",
      jobName: "Nightly",
      totalCount: 3,
      totalSize: 2_469_606_195,
      durationMs: 184_000,
      sources: [
        { name: "shop-mysql", sizeBytes: 1_932_735_283 },
        { name: "acme-uploads", sizeBytes: 503_316_480 },
        { name: "vardo-postgres", sizeBytes: 33_554_432 },
      ],
    },
  },
  {
    name: "backup-failed",
    event: {
      type: "backup.failed",
      title: "Backup failed: Nightly",
      message: "1 of 3 backup(s) failed for: shop-staging",
      jobId: "job_n1",
      jobName: "Nightly",
      failedCount: 1,
      totalCount: 3,
      errors: "shop-mysql: mysqldump: Got error: 2013: Lost connection to server during query",
      durationMs: 96_000,
    },
  },
  {
    name: "cron-failed",
    event: {
      type: "cron.failed",
      title: "Cron failed: sync-orders (Shop Staging)",
      message: "PHP Fatal error: Allowed memory size of 134217728 bytes exhausted",
      cronJobId: "cron_1",
      cronJobName: "sync-orders",
      appId: "app_wh4s",
      projectName: "Shop Staging",
      durationMs: 12_300,
      schedule: "*/15 * * * *",
      command: "wp cron event run --due-now",
      jobType: "command",
      exitCode: 255,
      target: "shop-staging-production-blue-wordpress-1",
      lastSuccessAt: "2026-10-09T16:45:00.000Z",
      logTail: [
        "Executed the cron event 'woocommerce_cleanup_sessions' in 0.012s.",
        "PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/wp-includes/class-wpdb.php on line 2349",
      ],
    },
  },
  {
    name: "cron-failed-exit",
    event: {
      type: "cron.failed",
      title: "Cron failed: failure test (Shop Docs)",
      message: "testing failure path",
      cronJobId: "cron_2",
      cronJobName: "failure test",
      appId: "app_d0cs",
      projectName: "Shop Docs",
      durationMs: 112,
      schedule: "* * * * *",
      command: "echo testing failure path; exit 3",
      jobType: "command",
      exitCode: 3,
      target: "shop-docs-production-green-web-1",
      logTail: ["testing failure path"],
    },
  },
  {
    name: "disk-write-alert",
    event: {
      type: "disk.write-alert",
      title: "High disk writes: MySQL",
      message: "App 'MySQL' wrote 7.7 GiB in the last hour (threshold: 4 GiB)",
      appId: "app_my5q",
      appName: "MySQL",
      projectName: "Shop Staging",
      composeService: "mysql",
      dataEngine: true,
      containerName: "shop-staging-data-production-blue-shop-staging-mysql-1",
      containerId: "c0ffee",
      writtenBytes: 8_270_499_840,
      thresholdBytes: 4_294_967_296,
      window: "1h",
    },
  },
  {
    name: "volume-drift",
    event: {
      type: "volume.drift",
      title: "Volume drift detected: shop-staging",
      message: "14 unignored file change(s) detected",
      appId: "app_wh4s",
      appName: "Shop Staging",
      totalDrift: 14,
      volumes: [
        { name: "wp-content", modified: 9, added: 3, missing: 0 },
        { name: "uploads", modified: 0, added: 0, missing: 2 },
      ],
    },
  },
  {
    name: "system-disk-alert",
    event: {
      type: "system.disk-alert",
      title: "Disk usage at 91%",
      message: "Vardo disk usage has reached 91% (threshold: 90%).",
      percent: 91.3,
      threshold: 90,
      severity: "warning",
      used: 219_043_332_096,
      total: 239_903_502_336,
    },
  },
  {
    name: "system-service-down",
    event: {
      type: "system.service-down",
      title: "Service degraded: redis",
      message: "redis (Cache and queues) is no longer responding.",
      service: "redis",
      description: "Cache and queues",
      latencyMs: "5003",
    },
  },
  {
    name: "system-cert-expiring",
    event: {
      type: "system.cert-expiring",
      title: "Certificate expiring: acme.org",
      message: "The certificate for acme.org and www.acme.org expires in 6 days and hasn't renewed.",
      domain: "acme.org",
      domains: ["acme.org", "www.acme.org"],
      daysLeft: 6,
      expiresAt: "2026-10-15T12:00:00.000Z",
      resolver: "le",
    },
  },
  {
    name: "weekly-digest",
    event: {
      type: "digest.weekly",
      title: "Weekly Digest — Joey Yax",
      message: "Weekly health summary",
      orgName: "Joey Yax",
      weekLabel: "Oct 2 – Oct 9, 2026",
      deploysTotal: 48,
      deploysSucceeded: 45,
      deploysFailed: 3,
      backupsTotal: 21,
      backupsSucceeded: 20,
      backupsFailed: 1,
      cronTotal: 2,
      cronFailed: 2,
      cronAffectedJobs: ["sync-orders"],
      diskWriteAlerts: 1,
      volumeDrifts: 0,
      projects: [
        { name: "Shop", deploys: 19, failures: 2, backupFailures: 1, cronFailures: 2 },
        { name: "Acme Nonprofit", deploys: 22, failures: 1, backupFailures: 0, cronFailures: 0 },
        { name: "Tools", deploys: 7, failures: 0, backupFailures: 0, cronFailures: 0 },
      ],
    },
  },
  {
    name: "system-shutdown",
    event: {
      type: "system.shutdown",
      title: "Vardo shutting down",
      message: "Vardo is shutting down: SIGTERM.",
      reason: "SIGTERM (host shutdown or container stop)",
      version: "0.1.0 (e36c2e3)",
      uptimeSeconds: 1_209_600,
    },
  },
  {
    name: "system-started",
    event: {
      type: "system.started",
      title: "Vardo started",
      message: "Vardo is back after 2 min 29 s.",
      version: "0.1.0 (e36c2e3)",
      downSeconds: 149,
      hostRebooted: true,
      reason: "SIGTERM (host shutdown or container stop)",
    },
  },
  {
    name: "system-recovered-unclean",
    event: {
      type: "system.recovered-unclean",
      title: "Vardo recovered after an unclean stop",
      message: "No clean-shutdown marker.",
      version: "0.1.0 (e36c2e3)",
      downSeconds: 412,
      hostRebooted: true,
      lastHeartbeatAt: "2026-10-09T16:51:30.000Z",
    },
  },
  {
    name: "system-update-started",
    event: {
      type: "system.update-started",
      title: "Vardo updating",
      message: "vardo update started.",
      fromVersion: "e36c2e3",
      branch: "main",
      fromSlot: "blue",
      toSlot: "green",
    },
  },
  {
    name: "system-updated",
    event: {
      type: "system.updated",
      title: "Vardo updated",
      message: "Updated e36c2e3 → 4f1a9b2.",
      fromVersion: "e36c2e3",
      toVersion: "4f1a9b2",
      fromSlot: "blue",
      toSlot: "green",
      durationSeconds: 212,
      downSeconds: 18,
    },
  },
  {
    name: "system-update-failed",
    event: {
      type: "system.update-failed",
      title: "Vardo update failed",
      message: "Health check failed.",
      fromVersion: "e36c2e3",
      toVersion: "4f1a9b2",
      fromSlot: "blue",
      toSlot: "green",
      step: "Health check",
      error: "New frontend did not become healthy within 120s. Rolled back to blue.",
      durationSeconds: 301,
      rolledBack: true,
      logTail: [
        "  [6/8] Swapping frontend",
        "  · Stopping old frontend...",
        "  · Starting new frontend...",
        "  [7/8] Health check",
        "  ! Health check failed — rolling back to blue slot",
        "  ✗ Update aborted: new frontend did not become healthy within 120s. Rolled back to blue slot.",
      ],
    },
  },
  {
    name: "system-containers-missing",
    event: {
      type: "system.containers-missing",
      title: "Containers didn't come back",
      message: "2 containers were running before the restart and aren't now.",
      containers: [
        { name: "search-data-production-green-meilisearch-1", app: "search-data", state: "exited" },
        { name: "shop-staging-production-blue-worker-1", app: "Shop Staging", state: "created" },
      ],
    },
  },
];
