import type { BusEventType, EventCategory } from "@/lib/bus/events";

export const CATEGORY_LABELS: Record<EventCategory, string> = {
  deploy: "Deploy",
  app: "App",
  alert: "Alerts",
  backup: "Backup",
  cron: "Cron",
  volume: "Volume",
  disk: "Disk",
  org: "Organization",
  security: "Security",
  system: "System",
  lifecycle: "Vardo lifecycle",
  digest: "Digest",
};

export const EVENT_LABELS: Record<BusEventType, string> = {
  "deploy.success": "Deploy succeeded",
  "deploy.failed": "Deploy failed",
  "deploy.incomplete": "Post-deploy work unfinished",
  "deploy.rollback": "Auto-rollback",
  "deploy.status": "Deploy status changed",
  "app.state-changed": "App state changed",
  "app.auto-restarted": "Container auto-restarted",
  "app.oom-killed": "Killed for memory",
  "alert.fired": "Host or app alert",
  "alert.resolved": "Alert resolved",
  "backup.success": "Backup succeeded",
  "backup.failed": "Backup failed",
  "backup.summary": "Backup summary",
  "backup.progress": "Backup progress",
  "cron.failed": "Cron job failed",
  "volume.drift": "Volume differs from image",
  "disk.write-alert": "High disk writes",
  "org.invitation-sent": "Invitation sent",
  "org.invitation-accepted": "Invitation accepted",
  "security.file-exposed": "Sensitive file exposed",
  "security.scan-findings": "Security scan findings",
  "security.domain-claimed": "Domain claimed by its owner",
  "system.service-down": "Service down",
  "system.restart-loop": "Vardo restarted",
  "system.cert-expiring": "Certificate expiring",
  "system.update-available": "Update available",
  "system.shutdown": "Vardo shutting down",
  "system.started": "Vardo started",
  "system.recovered-unclean": "Recovered after an unclean stop",
  "system.update-started": "Update started",
  "system.updated": "Update finished",
  "system.update-failed": "Update failed",
  "system.containers-missing": "Containers missing after restart",
  "digest.weekly": "Weekly digest",
};
