import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import {
  tasks,
  projects,
  clients,
  timeEntries,
  activities,
  invoices,
  inboxItems,
  taskRelationships,
  documents,
  projectExpenses,
  userSettings,
} from "@/lib/db/schema";
import { requireOrg } from "@/lib/auth/session";
import { getAccessibleProjectIds } from "@/lib/auth/permissions";
import {
  eq,
  and,
  or,
  inArray,
  isNull,
  isNotNull,
  gte,
  lte,
  ne,
  sql,
  sum,
  count,
  not,
} from "drizzle-orm";
import { fetchCalendarEvents, type CalendarEvent } from "@/lib/calendar";
import type {
  MyWorkData,
  WorkItem,
  ActivityItem,
  WorkloadSummary,
} from "@/lib/types/my-work";

type RouteParams = {
  params: Promise<{ orgId: string }>;
};

// GET /api/v1/organizations/[orgId]/my-work
export async function GET(request: NextRequest, { params }: RouteParams) {
  try {
    const { orgId } = await params;
    const { organization, session, membership } = await requireOrg();

    if (organization.id !== orgId) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const userId = session.user.id;
    const accessibleProjectIds = await getAccessibleProjectIds(
      userId,
      membership.role
    );

    // Date calculations — use local dates consistently for date column comparisons
    const now = new Date();
    const startOfToday = new Date(
      now.getFullYear(),
      now.getMonth(),
      now.getDate()
    );
    const todayStr = formatLocalDate(startOfToday);
    const startOfWeek = new Date(startOfToday);
    startOfWeek.setDate(startOfToday.getDate() - startOfToday.getDay()); // Sunday
    const startOfWeekStr = formatLocalDate(startOfWeek);
    const endOfWeek = new Date(startOfWeek);
    endOfWeek.setDate(startOfWeek.getDate() + 6);
    const endOfWeekStr = formatLocalDate(endOfWeek);
    const sevenDaysAgo = new Date(now);
    sevenDaysAgo.setDate(now.getDate() - 7);
    const thirtyDaysFromNow = new Date(startOfToday);
    thirtyDaysFromNow.setDate(startOfToday.getDate() + 30);
    const thirtyDaysFromNowStr = formatLocalDate(thirtyDaysFromNow);

    // Get org clients and project IDs for scoping
    const orgClients = await db.query.clients.findMany({
      where: eq(clients.organizationId, orgId),
      columns: { id: true, assignedTo: true },
    });

    const clientIds = orgClients.map((c) => c.id);
    if (clientIds.length === 0) {
      return NextResponse.json(emptyResponse());
    }

    const orgProjects = await db.query.projects.findMany({
      where: inArray(projects.clientId, clientIds),
      columns: { id: true },
    });

    let projectIds = orgProjects.map((p) => p.id);

    // Members can only see tasks in their assigned projects
    if (accessibleProjectIds !== null) {
      projectIds = projectIds.filter((id) =>
        accessibleProjectIds.includes(id)
      );
    }

    if (projectIds.length === 0) {
      return NextResponse.json(emptyResponse());
    }

    // Client IDs owned by current user (for invoice ownership)
    const myClientIds = orgClients
      .filter((c) => c.assignedTo === userId)
      .map((c) => c.id);

    // Run all queries in parallel
    const [
      summary,
      myActiveTasks,
      myInvoices,
      triageItems,
      blockedTaskIds,
      unassignedTasks,
      unassignedInbox,
      pendingProposals,
      pendingContracts,
      unpaidExpenses,
      recentActivities,
    ] = await Promise.all([
      // 1. Summary stats
      buildSummary(orgId, userId, todayStr, startOfWeekStr, endOfWeekStr, startOfToday, startOfWeek, projectIds, myClientIds),

      // 2. All my active tasks (assigned to me, not done, not archived)
      db.query.tasks.findMany({
        where: and(
          inArray(tasks.projectId, projectIds),
          eq(tasks.assignedTo, userId),
          isNotNull(tasks.status),
          ne(tasks.status, "done"),
          eq(tasks.isArchived, false)
        ),
        with: {
          project: {
            columns: { id: true, name: true },
            with: { client: { columns: { id: true, name: true, color: true } } },
          },
        },
      }),

      // 3. My invoices (not paid, not voided, excluding auto-generated drafts)
      myClientIds.length > 0
        ? db.query.invoices.findMany({
            where: and(
              eq(invoices.organizationId, orgId),
              inArray(invoices.clientId, myClientIds),
              not(inArray(invoices.status, ["paid", "voided"])),
              sql`NOT (${invoices.isAutoGenerated} = true AND ${invoices.status} = 'draft')`
            ),
            with: {
              client: { columns: { id: true, name: true, color: true } },
            },
          })
        : Promise.resolve([]),

      // 4. Needs Triage inbox items
      db.query.inboxItems.findMany({
        where: and(
          eq(inboxItems.organizationId, orgId),
          eq(inboxItems.status, "needs_review"),
          or(
            eq(inboxItems.assignedTo, userId),
            isNull(inboxItems.assignedTo)
          )
        ),
        with: {
          project: {
            columns: { id: true, name: true },
            with: { client: { columns: { id: true, name: true, color: true } } },
          },
        },
      }),

      // 5. Blocked task IDs — tasks where I'm assigned AND blocked by an incomplete task
      db
        .selectDistinct({ sourceTaskId: taskRelationships.sourceTaskId })
        .from(taskRelationships)
        .innerJoin(tasks, eq(taskRelationships.sourceTaskId, tasks.id))
        .where(
          and(
            eq(taskRelationships.type, "blocked_by"),
            eq(tasks.assignedTo, userId),
            inArray(tasks.projectId, projectIds),
            eq(tasks.isArchived, false),
            isNotNull(tasks.status),
            ne(tasks.status, "done"),
            sql`EXISTS (
              SELECT 1 FROM tasks AS target
              WHERE target.id = ${taskRelationships.targetTaskId}
                AND (target.status IS NULL OR target.status != 'done')
            )`
          )
        ),

      // 6. Unassigned tasks
      db.query.tasks.findMany({
        where: and(
          inArray(tasks.projectId, projectIds),
          isNull(tasks.assignedTo),
          isNotNull(tasks.status),
          ne(tasks.status, "done"),
          eq(tasks.isArchived, false)
        ),
        with: {
          project: {
            columns: { id: true, name: true },
            with: { client: { columns: { id: true, name: true, color: true } } },
          },
        },
      }),

      // 6. Unassigned inbox items
      db.query.inboxItems.findMany({
        where: and(
          eq(inboxItems.organizationId, orgId),
          isNull(inboxItems.assignedTo),
          eq(inboxItems.status, "needs_review")
        ),
        with: {
          project: {
            columns: { id: true, name: true },
            with: { client: { columns: { id: true, name: true, color: true } } },
          },
        },
      }),

      // 7. Proposals awaiting response
      db.query.documents.findMany({
        where: and(
          inArray(documents.projectId, projectIds),
          eq(documents.type, "proposal"),
          inArray(documents.status, ["sent", "viewed"])
        ),
        with: {
          project: {
            columns: { id: true, name: true },
            with: { client: { columns: { id: true, name: true, color: true } } },
          },
        },
      }),

      // 8. Contracts needing action
      db.query.documents.findMany({
        where: and(
          inArray(documents.projectId, projectIds),
          eq(documents.type, "contract"),
          inArray(documents.status, ["sent", "viewed"])
        ),
        with: {
          project: {
            columns: { id: true, name: true },
            with: { client: { columns: { id: true, name: true, color: true } } },
          },
        },
      }),

      // 9. Unpaid expenses
      db.query.projectExpenses.findMany({
        where: and(
          eq(projectExpenses.organizationId, orgId),
          eq(projectExpenses.createdBy, userId),
          eq(projectExpenses.status, "unpaid")
        ),
        with: {
          project: {
            columns: { id: true, name: true },
            with: { client: { columns: { id: true, name: true, color: true } } },
          },
        },
      }),

      // 10. Recent activity
      db.query.activities.findMany({
        where: and(
          eq(activities.organizationId, orgId),
          eq(activities.actorId, userId),
          gte(activities.createdAt, sevenDaysAgo)
        ),
        with: {
          project: { columns: { id: true, name: true } },
          task: { columns: { id: true, name: true } },
        },
        orderBy: (activities, { desc }) => [desc(activities.createdAt)],
        limit: 20,
      }),
    ]);

    // Fetch calendar events (depends on user settings, so runs after main queries)
    const userSettingsRow = await db.query.userSettings.findFirst({
      where: eq(userSettings.userId, userId),
    });

    const calendarEvents = userSettingsRow?.calendarIcsUrl
      ? await fetchCalendarEvents(
          userSettingsRow.calendarIcsUrl,
          startOfToday,
          thirtyDaysFromNow
        )
      : [];

    // Build blocked set for task classification
    const blockedIds = new Set(blockedTaskIds.map((r) => r.sourceTaskId));

    // Filter triage inbox items by accessible projects
    const filteredTriageItems = triageItems.filter(
      (item) => !item.projectId || projectIds.includes(item.projectId)
    );

    // Filter unassigned inbox by accessible projects, excluding items already in triage
    const triageItemIds = new Set(filteredTriageItems.map((item) => item.id));
    const filteredUnassignedInbox = unassignedInbox.filter(
      (item) =>
        !triageItemIds.has(item.id) &&
        (!item.projectId || projectIds.includes(item.projectId))
    );

    // Build time-based buckets
    const buckets: Record<string, WorkItem[]> = {
      overdue: [],
      today: [],
      thisWeek: [],
      upcoming: [],
      needsAttention: [],
    };

    // Classify tasks into buckets
    for (const task of myActiveTasks) {
      const item = mapTaskToWorkItem(task);

      if (blockedIds.has(task.id)) {
        buckets.needsAttention.push(item);
      } else {
        buckets[assignToBucket(task.dueDate, todayStr, endOfWeekStr, thirtyDaysFromNowStr)].push(item);
      }
    }

    // Classify invoices into buckets
    for (const invoice of myInvoices) {
      const item = mapInvoiceToWorkItem(invoice);
      buckets[assignToBucket(invoice.dueDate, todayStr, endOfWeekStr, thirtyDaysFromNowStr)].push(item);
    }

    // Triage items -> needsAttention
    for (const inboxItem of filteredTriageItems) {
      buckets.needsAttention.push(mapInboxToWorkItem(inboxItem));
    }

    // Unassigned items -> needsAttention
    for (const task of unassignedTasks) {
      buckets.needsAttention.push(mapTaskToWorkItem(task));
    }
    for (const inboxItem of filteredUnassignedInbox) {
      buckets.needsAttention.push(mapInboxToWorkItem(inboxItem));
    }

    // Proposals/contracts awaiting response -> needsAttention
    for (const doc of pendingProposals) {
      buckets.needsAttention.push(mapDocumentToWorkItem(doc));
    }
    for (const doc of pendingContracts) {
      buckets.needsAttention.push(mapDocumentToWorkItem(doc));
    }

    // Unpaid expenses -> needsAttention
    for (const expense of unpaidExpenses) {
      buckets.needsAttention.push(mapExpenseToWorkItem(expense));
    }

    // Calendar events -> bucket based on start date
    for (const event of calendarEvents) {
      const item = mapCalendarEventToWorkItem(event);
      const startDate = new Date(event.start);
      const startStr = formatLocalDate(startDate);
      // Calendar events are never overdue (past events are irrelevant)
      if (startStr < todayStr) continue;
      buckets[assignToBucket(startStr, todayStr, endOfWeekStr, thirtyDaysFromNowStr)].push(item);
    }

    const response: MyWorkData = {
      summary,
      overdue: buckets.overdue,
      today: buckets.today,
      thisWeek: buckets.thisWeek,
      upcoming: buckets.upcoming,
      needsAttention: buckets.needsAttention,
      recentActivity: recentActivities.map(mapActivity),
    };

    return NextResponse.json(response);
  } catch (error) {
    if (error instanceof Error && error.message === "Unauthorized") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    if (error instanceof Error && error.message === "No organization found") {
      return NextResponse.json(
        { error: "No organization found" },
        { status: 404 }
      );
    }
    console.error("Error fetching my-work:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

// ---------- Bucket assignment ----------

function assignToBucket(
  dueDate: string | null,
  todayStr: string,
  endOfWeekStr: string,
  thirtyDaysStr: string
): "overdue" | "today" | "thisWeek" | "upcoming" | "needsAttention" {
  if (!dueDate) return "needsAttention";
  if (dueDate < todayStr) return "overdue";
  if (dueDate === todayStr) return "today";
  if (dueDate <= endOfWeekStr) return "thisWeek";
  return "upcoming";
}

// ---------- Summary builder ----------

async function buildSummary(
  orgId: string,
  userId: string,
  todayStr: string,
  startOfWeekStr: string,
  endOfWeekStr: string,
  startOfToday: Date,
  startOfWeek: Date,
  projectIds: string[],
  myClientIds: string[]
): Promise<WorkloadSummary> {
  const [
    todayTimeResult,
    weekTimeResult,
    todayCompletedResult,
    weekCompletedResult,
    tasksRemainingResult,
    dueSoonTasksResult,
    dueSoonInvoicesResult,
    estimateResult,
    unbilledResult,
    outstandingResult,
    pendingExpensesResult,
  ] = await Promise.all([
    // Today's tracked time
    db
      .select({ total: sum(timeEntries.durationMinutes) })
      .from(timeEntries)
      .where(
        and(
          eq(timeEntries.organizationId, orgId),
          eq(timeEntries.userId, userId),
          eq(timeEntries.date, todayStr)
        )
      ),

    // This week's tracked time
    db
      .select({ total: sum(timeEntries.durationMinutes) })
      .from(timeEntries)
      .where(
        and(
          eq(timeEntries.organizationId, orgId),
          eq(timeEntries.userId, userId),
          gte(timeEntries.date, startOfWeekStr),
          lte(timeEntries.date, endOfWeekStr)
        )
      ),

    // Tasks completed today (via activities)
    db
      .select({ total: count() })
      .from(activities)
      .where(
        and(
          eq(activities.organizationId, orgId),
          eq(activities.actorId, userId),
          eq(activities.action, "status_changed"),
          eq(activities.newValue, "done"),
          gte(activities.createdAt, startOfToday)
        )
      ),

    // Tasks completed this week
    db
      .select({ total: count() })
      .from(activities)
      .where(
        and(
          eq(activities.organizationId, orgId),
          eq(activities.actorId, userId),
          eq(activities.action, "status_changed"),
          eq(activities.newValue, "done"),
          gte(activities.createdAt, startOfWeek)
        )
      ),

    // Tasks remaining (assigned, not done, not archived, has status)
    db
      .select({ total: count() })
      .from(tasks)
      .where(
        and(
          inArray(tasks.projectId, projectIds),
          eq(tasks.assignedTo, userId),
          isNotNull(tasks.status),
          ne(tasks.status, "done"),
          eq(tasks.isArchived, false)
        )
      ),

    // Tasks due this week
    db
      .select({ total: count() })
      .from(tasks)
      .where(
        and(
          inArray(tasks.projectId, projectIds),
          eq(tasks.assignedTo, userId),
          isNotNull(tasks.status),
          ne(tasks.status, "done"),
          eq(tasks.isArchived, false),
          isNotNull(tasks.dueDate),
          gte(tasks.dueDate, startOfWeekStr),
          lte(tasks.dueDate, endOfWeekStr)
        )
      ),

    // Invoices due this week (count via client ownership)
    db
      .select({ total: count() })
      .from(invoices)
      .innerJoin(clients, eq(invoices.clientId, clients.id))
      .where(
        and(
          eq(invoices.organizationId, orgId),
          eq(clients.assignedTo, userId),
          isNotNull(invoices.dueDate),
          gte(invoices.dueDate, startOfWeekStr),
          lte(invoices.dueDate, endOfWeekStr),
          not(inArray(invoices.status, ["paid", "voided"])),
          sql`NOT (${invoices.isAutoGenerated} = true AND ${invoices.status} = 'draft')`
        )
      ),

    // Estimated minutes for tasks due this week
    db
      .select({ total: sum(tasks.estimateMinutes) })
      .from(tasks)
      .where(
        and(
          inArray(tasks.projectId, projectIds),
          eq(tasks.assignedTo, userId),
          isNotNull(tasks.status),
          ne(tasks.status, "done"),
          eq(tasks.isArchived, false),
          isNotNull(tasks.dueDate),
          gte(tasks.dueDate, startOfWeekStr),
          lte(tasks.dueDate, endOfWeekStr)
        )
      ),

    // Unbilled time: entries where isBillableOverride is not explicitly false,
    // and the entry is not referenced in any non-draft/voided invoice line item
    db
      .select({ total: sum(timeEntries.durationMinutes) })
      .from(timeEntries)
      .where(
        and(
          eq(timeEntries.organizationId, orgId),
          eq(timeEntries.userId, userId),
          or(
            isNull(timeEntries.isBillableOverride),
            eq(timeEntries.isBillableOverride, true)
          ),
          sql`NOT EXISTS (
            SELECT 1 FROM invoice_line_items ili
            INNER JOIN invoices inv ON inv.id = ili.invoice_id
            WHERE ili.entry_ids @> jsonb_build_array(${timeEntries.id}::text)
              AND inv.status NOT IN ('draft', 'voided')
          )`
        )
      ),

    // Outstanding invoices (sent, not paid/voided/draft)
    myClientIds.length > 0
      ? db
          .select({ total: sum(invoices.subtotal) })
          .from(invoices)
          .innerJoin(clients, eq(invoices.clientId, clients.id))
          .where(
            and(
              eq(invoices.organizationId, orgId),
              eq(clients.assignedTo, userId),
              not(inArray(invoices.status, ["paid", "voided", "draft"]))
            )
          )
      : Promise.resolve([{ total: null }]),

    // Pending expenses (unpaid)
    db
      .select({ total: sum(projectExpenses.amountCents) })
      .from(projectExpenses)
      .where(
        and(
          eq(projectExpenses.organizationId, orgId),
          eq(projectExpenses.createdBy, userId),
          eq(projectExpenses.status, "unpaid")
        )
      ),
  ]);

  return {
    today: {
      minutesTracked: Number(todayTimeResult[0]?.total) || 0,
      tasksCompleted: Number(todayCompletedResult[0]?.total) || 0,
    },
    thisWeek: {
      minutesTracked: Number(weekTimeResult[0]?.total) || 0,
      tasksCompleted: Number(weekCompletedResult[0]?.total) || 0,
      tasksRemaining: Number(tasksRemainingResult[0]?.total) || 0,
    },
    upcoming: {
      itemsDueThisWeek:
        (Number(dueSoonTasksResult[0]?.total) || 0) +
        (Number(dueSoonInvoicesResult[0]?.total) || 0),
      estimatedMinutes: Number(estimateResult[0]?.total) || 0,
    },
    money: {
      unbilledMinutes: Number(unbilledResult[0]?.total) || 0,
      outstandingInvoiceCents: Number(outstandingResult[0]?.total) || 0,
      pendingExpenseCents: Number(pendingExpensesResult[0]?.total) || 0,
    },
  };
}

// ---------- Mappers ----------

type TaskWithProject = {
  id: string;
  name: string;
  status: string | null;
  priority: string | null;
  dueDate: string | null;
  estimateMinutes: number | null;
  project: {
    id: string;
    name: string;
    client: { id: string; name: string; color: string | null } | null;
  } | null;
};

function mapTaskToWorkItem(task: TaskWithProject): WorkItem {
  return {
    type: "task",
    id: task.id,
    title: task.name,
    dueDate: task.dueDate,
    status: task.status ?? "unknown",
    priority: task.priority,
    estimateMinutes: task.estimateMinutes,
    project: task.project
      ? {
          id: task.project.id,
          name: task.project.name,
          client: task.project.client ?? undefined,
        }
      : null,
  };
}

type InvoiceWithClient = {
  id: string;
  invoiceNumber: string;
  status: string | null;
  dueDate: string | null;
  client: { id: string; name: string; color: string | null } | null;
};

function mapInvoiceToWorkItem(invoice: InvoiceWithClient): WorkItem {
  return {
    type: "invoice",
    id: invoice.id,
    title: `Invoice ${invoice.invoiceNumber}`,
    dueDate: invoice.dueDate,
    status: invoice.status ?? "draft",
    project: invoice.client
      ? {
          id: "",
          name: "",
          client: {
            id: invoice.client.id,
            name: invoice.client.name,
            color: invoice.client.color,
          },
        }
      : null,
  };
}

type InboxWithProject = {
  id: string;
  subject: string | null;
  status: string | null;
  projectId: string | null;
  project: {
    id: string;
    name: string;
    client: { id: string; name: string; color: string | null } | null;
  } | null;
};

function mapInboxToWorkItem(item: InboxWithProject): WorkItem {
  return {
    type: "inbox_item",
    id: item.id,
    title: item.subject ?? "Untitled",
    dueDate: null,
    status: item.status ?? "needs_review",
    project: item.project
      ? {
          id: item.project.id,
          name: item.project.name,
          client: item.project.client ?? undefined,
        }
      : null,
  };
}

type DocumentWithProject = {
  id: string;
  type: string;
  title: string;
  status: string;
  sentAt: Date | null;
  project: {
    id: string;
    name: string;
    client: { id: string; name: string; color: string | null } | null;
  } | null;
};

function mapDocumentToWorkItem(doc: DocumentWithProject): WorkItem {
  return {
    type: doc.type === "proposal" ? "proposal" : "contract",
    id: doc.id,
    title: doc.title || `${doc.type === "proposal" ? "Proposal" : "Contract"} (untitled)`,
    dueDate: doc.sentAt ? formatLocalDate(doc.sentAt) : null,
    status: doc.status ?? "draft",
    project: doc.project
      ? {
          id: doc.project.id,
          name: doc.project.name,
          client: doc.project.client ?? undefined,
        }
      : null,
  };
}

type ExpenseWithProject = {
  id: string;
  description: string;
  date: string;
  status: string | null;
  amountCents: number;
  project: {
    id: string;
    name: string;
    client: { id: string; name: string; color: string | null } | null;
  } | null;
};

function mapExpenseToWorkItem(expense: ExpenseWithProject): WorkItem {
  return {
    type: "expense",
    id: expense.id,
    title: expense.description,
    dueDate: expense.date,
    status: expense.status ?? "unpaid",
    amountCents: expense.amountCents,
    project: expense.project
      ? {
          id: expense.project.id,
          name: expense.project.name,
          client: expense.project.client ?? undefined,
        }
      : null,
  };
}

function mapCalendarEventToWorkItem(event: CalendarEvent): WorkItem {
  return {
    type: "calendar_event",
    id: event.id,
    title: event.title,
    dueDate: formatLocalDate(new Date(event.start)),
    status: "scheduled",
    startTime: event.start,
    endTime: event.end,
    allDay: event.allDay,
    location: event.location,
  };
}

type ActivityWithRelations = {
  id: string;
  action: string;
  entityType: string;
  entityId: string;
  field: string | null;
  oldValue: string | null;
  newValue: string | null;
  createdAt: Date;
  project: { id: string; name: string } | null;
  task: { id: string; name: string } | null;
};

function mapActivity(activity: ActivityWithRelations): ActivityItem {
  return {
    id: activity.id,
    action: activity.action,
    entityType: activity.entityType,
    entityId: activity.entityId,
    field: activity.field,
    oldValue: activity.oldValue,
    newValue: activity.newValue,
    createdAt: activity.createdAt.toISOString(),
    project: activity.project,
    task: activity.task,
  };
}

// ---------- Helpers ----------

function formatLocalDate(date: Date): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}

function emptyResponse(): MyWorkData {
  return {
    summary: {
      today: { minutesTracked: 0, tasksCompleted: 0 },
      thisWeek: { minutesTracked: 0, tasksCompleted: 0, tasksRemaining: 0 },
      upcoming: { itemsDueThisWeek: 0, estimatedMinutes: 0 },
      money: { unbilledMinutes: 0, outstandingInvoiceCents: 0, pendingExpenseCents: 0 },
    },
    overdue: [],
    today: [],
    thisWeek: [],
    upcoming: [],
    needsAttention: [],
    recentActivity: [],
  };
}
