import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import {
  tasks,
  projects,
  clients,
  timeEntries,
  activities,
  invoices,
  inboxItems,
  taskRelationships,
} from "@/lib/db/schema";
import { requireOrg } from "@/lib/auth/session";
import { getAccessibleProjectIds } from "@/lib/auth/permissions";
import {
  eq,
  and,
  or,
  inArray,
  isNull,
  isNotNull,
  gte,
  lte,
  lt,
  ne,
  sql,
  sum,
  count,
  not,
} from "drizzle-orm";
import type {
  MyWorkData,
  WorkItem,
  ActivityItem,
  WorkloadSummary,
} from "@/lib/types/my-work";

type RouteParams = {
  params: Promise<{ orgId: string }>;
};

// GET /api/v1/organizations/[orgId]/my-work
export async function GET(request: NextRequest, { params }: RouteParams) {
  try {
    const { orgId } = await params;
    const { organization, session, membership } = await requireOrg();

    if (organization.id !== orgId) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const userId = session.user.id;
    const accessibleProjectIds = await getAccessibleProjectIds(
      userId,
      membership.role
    );

    // Date calculations
    const now = new Date();
    const todayStr = now.toISOString().split("T")[0];
    const startOfToday = new Date(
      now.getFullYear(),
      now.getMonth(),
      now.getDate()
    );
    const startOfWeek = new Date(startOfToday);
    startOfWeek.setDate(startOfToday.getDate() - startOfToday.getDay()); // Sunday
    const startOfWeekStr = startOfWeek.toISOString().split("T")[0];
    const endOfWeek = new Date(startOfWeek);
    endOfWeek.setDate(startOfWeek.getDate() + 6);
    const endOfWeekStr = endOfWeek.toISOString().split("T")[0];
    const sevenDaysFromNow = new Date(startOfToday);
    sevenDaysFromNow.setDate(startOfToday.getDate() + 7);
    const sevenDaysFromNowStr = sevenDaysFromNow.toISOString().split("T")[0];
    const sevenDaysAgo = new Date(now);
    sevenDaysAgo.setDate(now.getDate() - 7);

    // Get org clients and project IDs for scoping
    const orgClients = await db.query.clients.findMany({
      where: eq(clients.organizationId, orgId),
      columns: { id: true, assignedTo: true },
    });

    const clientIds = orgClients.map((c) => c.id);
    if (clientIds.length === 0) {
      return NextResponse.json(emptyResponse());
    }

    const orgProjects = await db.query.projects.findMany({
      where: inArray(projects.clientId, clientIds),
      columns: { id: true },
    });

    let projectIds = orgProjects.map((p) => p.id);

    // Members can only see tasks in their assigned projects
    if (accessibleProjectIds !== null) {
      projectIds = projectIds.filter((id) =>
        accessibleProjectIds.includes(id)
      );
    }

    if (projectIds.length === 0) {
      return NextResponse.json(emptyResponse());
    }

    // Client IDs owned by current user (for invoice ownership)
    const myClientIds = orgClients
      .filter((c) => c.assignedTo === userId)
      .map((c) => c.id);

    // Run all queries in parallel
    const [
      summary,
      pastDueTasks,
      pastDueInvoices,
      dueSoonTasks,
      dueSoonInvoices,
      triageItems,
      blockedTaskIds,
      allMyTasks,
      unassignedTasks,
      unassignedInbox,
      recentActivities,
    ] = await Promise.all([
      // 1. Summary stats
      buildSummary(orgId, userId, todayStr, startOfWeekStr, endOfWeekStr, startOfToday, startOfWeek, projectIds),

      // 2. Past Due tasks
      db.query.tasks.findMany({
        where: and(
          inArray(tasks.projectId, projectIds),
          eq(tasks.assignedTo, userId),
          isNotNull(tasks.status),
          ne(tasks.status, "done"),
          eq(tasks.isArchived, false),
          isNotNull(tasks.dueDate),
          lt(tasks.dueDate, todayStr)
        ),
        with: {
          project: {
            columns: { id: true, name: true },
            with: { client: { columns: { id: true, name: true, color: true } } },
          },
        },
      }),

      // 2. Past Due invoices
      myClientIds.length > 0
        ? db.query.invoices.findMany({
            where: and(
              eq(invoices.organizationId, orgId),
              inArray(invoices.clientId, myClientIds),
              isNotNull(invoices.dueDate),
              lt(invoices.dueDate, todayStr),
              not(inArray(invoices.status, ["paid", "voided"])),
              // Exclude auto-generated drafts
              sql`NOT (${invoices.isAutoGenerated} = true AND ${invoices.status} = 'draft')`
            ),
            with: {
              client: { columns: { id: true, name: true, color: true } },
            },
          })
        : Promise.resolve([]),

      // 3. Due Soon tasks
      db.query.tasks.findMany({
        where: and(
          inArray(tasks.projectId, projectIds),
          eq(tasks.assignedTo, userId),
          isNotNull(tasks.status),
          ne(tasks.status, "done"),
          eq(tasks.isArchived, false),
          isNotNull(tasks.dueDate),
          gte(tasks.dueDate, todayStr),
          lte(tasks.dueDate, sevenDaysFromNowStr)
        ),
        with: {
          project: {
            columns: { id: true, name: true },
            with: { client: { columns: { id: true, name: true, color: true } } },
          },
        },
      }),

      // 3. Due Soon invoices
      myClientIds.length > 0
        ? db.query.invoices.findMany({
            where: and(
              eq(invoices.organizationId, orgId),
              inArray(invoices.clientId, myClientIds),
              isNotNull(invoices.dueDate),
              gte(invoices.dueDate, todayStr),
              lte(invoices.dueDate, sevenDaysFromNowStr),
              not(inArray(invoices.status, ["paid", "voided"])),
              sql`NOT (${invoices.isAutoGenerated} = true AND ${invoices.status} = 'draft')`
            ),
            with: {
              client: { columns: { id: true, name: true, color: true } },
            },
          })
        : Promise.resolve([]),

      // 4. Needs Triage
      db.query.inboxItems.findMany({
        where: and(
          eq(inboxItems.organizationId, orgId),
          eq(inboxItems.status, "needs_review"),
          or(
            eq(inboxItems.assignedTo, userId),
            isNull(inboxItems.assignedTo)
          )
        ),
        with: {
          project: {
            columns: { id: true, name: true },
            with: { client: { columns: { id: true, name: true, color: true } } },
          },
        },
      }),

      // 5. Blocked task IDs — find tasks where I'm assigned AND blocked by an incomplete task
      db
        .selectDistinct({ sourceTaskId: taskRelationships.sourceTaskId })
        .from(taskRelationships)
        .innerJoin(tasks, eq(taskRelationships.sourceTaskId, tasks.id))
        .where(
          and(
            eq(taskRelationships.type, "blocked_by"),
            eq(tasks.assignedTo, userId),
            inArray(tasks.projectId, projectIds),
            eq(tasks.isArchived, false),
            isNotNull(tasks.status),
            ne(tasks.status, "done"),
            // Target task (blocker) is not done
            sql`EXISTS (
              SELECT 1 FROM tasks AS target
              WHERE target.id = ${taskRelationships.targetTaskId}
                AND (target.status IS NULL OR target.status != 'done')
            )`
          )
        ),

      // 6. All my active tasks (for myItems — we'll filter out pastDue/dueSoon/blocked)
      db.query.tasks.findMany({
        where: and(
          inArray(tasks.projectId, projectIds),
          eq(tasks.assignedTo, userId),
          isNotNull(tasks.status),
          ne(tasks.status, "done"),
          eq(tasks.isArchived, false)
        ),
        with: {
          project: {
            columns: { id: true, name: true },
            with: { client: { columns: { id: true, name: true, color: true } } },
          },
        },
      }),

      // 7. Unassigned tasks
      db.query.tasks.findMany({
        where: and(
          inArray(tasks.projectId, projectIds),
          isNull(tasks.assignedTo),
          isNotNull(tasks.status),
          ne(tasks.status, "done"),
          eq(tasks.isArchived, false)
        ),
        with: {
          project: {
            columns: { id: true, name: true },
            with: { client: { columns: { id: true, name: true, color: true } } },
          },
        },
      }),

      // 7. Unassigned inbox items
      db.query.inboxItems.findMany({
        where: and(
          eq(inboxItems.organizationId, orgId),
          isNull(inboxItems.assignedTo),
          eq(inboxItems.status, "needs_review")
        ),
        with: {
          project: {
            columns: { id: true, name: true },
            with: { client: { columns: { id: true, name: true, color: true } } },
          },
        },
      }),

      // 8. Recent activity
      db.query.activities.findMany({
        where: and(
          eq(activities.organizationId, orgId),
          eq(activities.actorId, userId),
          gte(activities.createdAt, sevenDaysAgo)
        ),
        with: {
          project: { columns: { id: true, name: true } },
          task: { columns: { id: true, name: true } },
        },
        orderBy: (activities, { desc }) => [desc(activities.createdAt)],
        limit: 20,
      }),
    ]);

    // Build blocked set for filtering
    const blockedIds = new Set(blockedTaskIds.map((r) => r.sourceTaskId));

    // Collect IDs already in pastDue/dueSoon/blocked to exclude from myItems
    const pastDueTaskIds = new Set(pastDueTasks.map((t) => t.id));
    const dueSoonTaskIds = new Set(dueSoonTasks.map((t) => t.id));
    const excludeFromMyItems = new Set([
      ...pastDueTaskIds,
      ...dueSoonTaskIds,
      ...blockedIds,
    ]);

    // Filter blocked tasks from allMyTasks for the blocked section
    const blockedTasks = allMyTasks.filter((t) => blockedIds.has(t.id));

    // MyItems = my tasks minus pastDue, dueSoon, blocked
    const myItems = allMyTasks.filter((t) => !excludeFromMyItems.has(t.id));

    // Filter triage inbox items by accessible projects
    const filteredTriageItems = triageItems.filter(
      (item) => !item.projectId || projectIds.includes(item.projectId)
    );

    // Filter unassigned inbox by accessible projects, excluding items already in triage
    const triageItemIds = new Set(filteredTriageItems.map((item) => item.id));
    const filteredUnassignedInbox = unassignedInbox.filter(
      (item) =>
        !triageItemIds.has(item.id) &&
        (!item.projectId || projectIds.includes(item.projectId))
    );

    // Map to response shape
    const response: MyWorkData = {
      summary,
      pastDue: [
        ...pastDueTasks.map(mapTaskToWorkItem),
        ...pastDueInvoices.map(mapInvoiceToWorkItem),
      ],
      dueSoon: [
        ...dueSoonTasks.map(mapTaskToWorkItem),
        ...dueSoonInvoices.map(mapInvoiceToWorkItem),
      ],
      needsTriage: filteredTriageItems.map(mapInboxToWorkItem),
      blocked: blockedTasks.map(mapTaskToWorkItem),
      myItems: myItems.map(mapTaskToWorkItem),
      unassigned: [
        ...unassignedTasks.map(mapTaskToWorkItem),
        ...filteredUnassignedInbox.map(mapInboxToWorkItem),
      ],
      recentActivity: recentActivities.map(mapActivity),
    };

    return NextResponse.json(response);
  } catch (error) {
    if (error instanceof Error && error.message === "Unauthorized") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    if (error instanceof Error && error.message === "No organization found") {
      return NextResponse.json(
        { error: "No organization found" },
        { status: 404 }
      );
    }
    console.error("Error fetching my-work:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}

// ---------- Summary builder ----------

async function buildSummary(
  orgId: string,
  userId: string,
  todayStr: string,
  startOfWeekStr: string,
  endOfWeekStr: string,
  startOfToday: Date,
  startOfWeek: Date,
  projectIds: string[]
): Promise<WorkloadSummary> {
  const [
    todayTimeResult,
    weekTimeResult,
    todayCompletedResult,
    weekCompletedResult,
    tasksRemainingResult,
    dueSoonTasksResult,
    dueSoonInvoicesResult,
    estimateResult,
  ] = await Promise.all([
    // Today's tracked time
    db
      .select({ total: sum(timeEntries.durationMinutes) })
      .from(timeEntries)
      .where(
        and(
          eq(timeEntries.organizationId, orgId),
          eq(timeEntries.userId, userId),
          eq(timeEntries.date, todayStr)
        )
      ),

    // This week's tracked time
    db
      .select({ total: sum(timeEntries.durationMinutes) })
      .from(timeEntries)
      .where(
        and(
          eq(timeEntries.organizationId, orgId),
          eq(timeEntries.userId, userId),
          gte(timeEntries.date, startOfWeekStr),
          lte(timeEntries.date, endOfWeekStr)
        )
      ),

    // Tasks completed today (via activities)
    db
      .select({ total: count() })
      .from(activities)
      .where(
        and(
          eq(activities.organizationId, orgId),
          eq(activities.actorId, userId),
          eq(activities.action, "status_changed"),
          eq(activities.newValue, "done"),
          gte(activities.createdAt, startOfToday)
        )
      ),

    // Tasks completed this week
    db
      .select({ total: count() })
      .from(activities)
      .where(
        and(
          eq(activities.organizationId, orgId),
          eq(activities.actorId, userId),
          eq(activities.action, "status_changed"),
          eq(activities.newValue, "done"),
          gte(activities.createdAt, startOfWeek)
        )
      ),

    // Tasks remaining (assigned, not done, not archived, has status)
    db
      .select({ total: count() })
      .from(tasks)
      .where(
        and(
          inArray(tasks.projectId, projectIds),
          eq(tasks.assignedTo, userId),
          isNotNull(tasks.status),
          ne(tasks.status, "done"),
          eq(tasks.isArchived, false)
        )
      ),

    // Tasks due this week
    db
      .select({ total: count() })
      .from(tasks)
      .where(
        and(
          inArray(tasks.projectId, projectIds),
          eq(tasks.assignedTo, userId),
          isNotNull(tasks.status),
          ne(tasks.status, "done"),
          eq(tasks.isArchived, false),
          isNotNull(tasks.dueDate),
          gte(tasks.dueDate, startOfWeekStr),
          lte(tasks.dueDate, endOfWeekStr)
        )
      ),

    // Invoices due this week (count via client ownership)
    db
      .select({ total: count() })
      .from(invoices)
      .innerJoin(clients, eq(invoices.clientId, clients.id))
      .where(
        and(
          eq(invoices.organizationId, orgId),
          eq(clients.assignedTo, userId),
          isNotNull(invoices.dueDate),
          gte(invoices.dueDate, startOfWeekStr),
          lte(invoices.dueDate, endOfWeekStr),
          not(inArray(invoices.status, ["paid", "voided"])),
          sql`NOT (${invoices.isAutoGenerated} = true AND ${invoices.status} = 'draft')`
        )
      ),

    // Estimated minutes for tasks due this week
    db
      .select({ total: sum(tasks.estimateMinutes) })
      .from(tasks)
      .where(
        and(
          inArray(tasks.projectId, projectIds),
          eq(tasks.assignedTo, userId),
          isNotNull(tasks.status),
          ne(tasks.status, "done"),
          eq(tasks.isArchived, false),
          isNotNull(tasks.dueDate),
          gte(tasks.dueDate, startOfWeekStr),
          lte(tasks.dueDate, endOfWeekStr)
        )
      ),
  ]);

  return {
    today: {
      minutesTracked: Number(todayTimeResult[0]?.total) || 0,
      tasksCompleted: Number(todayCompletedResult[0]?.total) || 0,
    },
    thisWeek: {
      minutesTracked: Number(weekTimeResult[0]?.total) || 0,
      tasksCompleted: Number(weekCompletedResult[0]?.total) || 0,
      tasksRemaining: Number(tasksRemainingResult[0]?.total) || 0,
    },
    upcoming: {
      itemsDueThisWeek:
        (Number(dueSoonTasksResult[0]?.total) || 0) +
        (Number(dueSoonInvoicesResult[0]?.total) || 0),
      estimatedMinutes: Number(estimateResult[0]?.total) || 0,
    },
  };
}

// ---------- Mappers ----------

type TaskWithProject = {
  id: string;
  name: string;
  status: string | null;
  priority: string | null;
  dueDate: string | null;
  estimateMinutes: number | null;
  project: {
    id: string;
    name: string;
    client: { id: string; name: string; color: string | null } | null;
  } | null;
};

function mapTaskToWorkItem(task: TaskWithProject): WorkItem {
  return {
    type: "task",
    id: task.id,
    title: task.name,
    dueDate: task.dueDate,
    status: task.status ?? "unknown",
    priority: task.priority,
    estimateMinutes: task.estimateMinutes,
    project: task.project
      ? {
          id: task.project.id,
          name: task.project.name,
          client: task.project.client ?? undefined,
        }
      : null,
  };
}

type InvoiceWithClient = {
  id: string;
  invoiceNumber: string;
  status: string | null;
  dueDate: string | null;
  client: { id: string; name: string; color: string | null } | null;
};

function mapInvoiceToWorkItem(invoice: InvoiceWithClient): WorkItem {
  return {
    type: "invoice",
    id: invoice.id,
    title: `Invoice ${invoice.invoiceNumber}`,
    dueDate: invoice.dueDate,
    status: invoice.status ?? "draft",
    project: invoice.client
      ? {
          id: "",
          name: "",
          client: {
            id: invoice.client.id,
            name: invoice.client.name,
            color: invoice.client.color,
          },
        }
      : null,
  };
}

type InboxWithProject = {
  id: string;
  subject: string | null;
  status: string | null;
  projectId: string | null;
  project: {
    id: string;
    name: string;
    client: { id: string; name: string; color: string | null } | null;
  } | null;
};

function mapInboxToWorkItem(item: InboxWithProject): WorkItem {
  return {
    type: "inbox_item",
    id: item.id,
    title: item.subject ?? "Untitled",
    dueDate: null,
    status: item.status ?? "needs_review",
    project: item.project
      ? {
          id: item.project.id,
          name: item.project.name,
          client: item.project.client ?? undefined,
        }
      : null,
  };
}

type ActivityWithRelations = {
  id: string;
  action: string;
  entityType: string;
  entityId: string;
  field: string | null;
  oldValue: string | null;
  newValue: string | null;
  createdAt: Date;
  project: { id: string; name: string } | null;
  task: { id: string; name: string } | null;
};

function mapActivity(activity: ActivityWithRelations): ActivityItem {
  return {
    id: activity.id,
    action: activity.action,
    entityType: activity.entityType,
    entityId: activity.entityId,
    field: activity.field,
    oldValue: activity.oldValue,
    newValue: activity.newValue,
    createdAt: activity.createdAt.toISOString(),
    project: activity.project,
    task: activity.task,
  };
}

// ---------- Helpers ----------

function emptyResponse(): MyWorkData {
  return {
    summary: {
      today: { minutesTracked: 0, tasksCompleted: 0 },
      thisWeek: { minutesTracked: 0, tasksCompleted: 0, tasksRemaining: 0 },
      upcoming: { itemsDueThisWeek: 0, estimatedMinutes: 0 },
    },
    pastDue: [],
    dueSoon: [],
    needsTriage: [],
    blocked: [],
    myItems: [],
    unassigned: [],
    recentActivity: [],
  };
}
