import { describe, it, expect, vi } from "vitest";
import {
  parseDokployEnv,
  toVardoEnv,
  parseSource,
  parseArgs,
  fetchDokployEnv,
  findVardoApp,
} from "@/scripts/dokploy-env-import";
import { parseEnvContent } from "@/lib/env/parse-env-content";

// All values are fake.
const FIXTURE = [
  "# generated by Dokploy",
  "NODE_ENV=production",
  "DATABASE_URL=postgres://app:fake-pass@db:5432/app",
  'QUOTED="hello world"',
  "SINGLE='single value'",
  "export EXPORTED=yes",
  "HASH=abc#def",
  "EMPTY=",
  "PADDED=\"  keep me  \"",
  'WRAPPED="\\"inner\\""',
  "SHARED=${{project.FAKE_SHARED}}",
  "DUP=first",
  "DUP=second",
  'PRIVATE_KEY="-----BEGIN FAKE-----',
  "line-two",
  '-----END FAKE-----"',
  "AFTER_MULTILINE=ok",
  "not a pair",
  "1BAD=x",
].join("\n");

describe("parseDokployEnv", () => {
  const map = new Map(parseDokployEnv(FIXTURE).map((e) => [e.key, e.value]));

  it("reads plain, quoted and exported pairs", () => {
    expect(map.get("NODE_ENV")).toBe("production");
    expect(map.get("QUOTED")).toBe("hello world");
    expect(map.get("SINGLE")).toBe("single value");
    expect(map.get("EXPORTED")).toBe("yes");
    expect(map.get("HASH")).toBe("abc#def");
    expect(map.get("EMPTY")).toBe("");
  });

  it("joins multi-line quoted values and keeps parsing after them", () => {
    expect(map.get("PRIVATE_KEY")).toBe("-----BEGIN FAKE-----\nline-two\n-----END FAKE-----");
    expect(map.get("AFTER_MULTILINE")).toBe("ok");
  });

  it("drops comments and malformed lines", () => {
    expect([...map.keys()]).not.toContain("1BAD");
    expect(map.size).toBe(13);
  });
});

describe("toVardoEnv", () => {
  const result = toVardoEnv(parseDokployEnv(FIXTURE));

  it("skips multi-line values by name", () => {
    expect(result.skipped).toEqual(["PRIVATE_KEY"]);
    expect(result.content).not.toContain("BEGIN FAKE");
  });

  it("flags Dokploy shared-variable references", () => {
    expect(result.unresolved).toEqual(["SHARED"]);
  });

  it("keeps the last duplicate", () => {
    expect(result.content).toContain("DUP=second\n");
    expect(result.content).not.toContain("DUP=first");
  });

  it("round-trips through Vardo's own env parser", () => {
    const back = new Map(parseEnvContent(result.content).map((e) => [e.key, e.value]));
    expect(back.get("QUOTED")).toBe("hello world");
    expect(back.get("DATABASE_URL")).toBe("postgres://app:fake-pass@db:5432/app");
    expect(back.get("HASH")).toBe("abc#def");
    expect(back.get("EMPTY")).toBe("");
    expect(back.get("PADDED")).toBe("  keep me  ");
    expect(back.get("WRAPPED")).toBe('\\"inner\\"');
    expect(back.has("PRIVATE_KEY")).toBe(false);
    expect(result.written).toHaveLength(12);
  });

  it("returns empty content for an empty env", () => {
    expect(toVardoEnv([]).content).toBe("");
  });
});

describe("parseSource and parseArgs", () => {
  it("parses application and compose sources", () => {
    expect(parseSource("application:abc")).toEqual({ kind: "application", id: "abc" });
    expect(parseSource("compose:xyz")).toEqual({ kind: "compose", id: "xyz" });
    expect(() => parseSource("abc")).toThrow();
  });

  it("parses flags and rejects unknown ones", () => {
    const a = parseArgs(["--from", "compose:1", "--app", "pouch", "--dry-run"]);
    expect(a).toMatchObject({ from: "compose:1", app: "pouch", dryRun: true, overwrite: false });
    expect(() => parseArgs(["--api-key", "x"])).toThrow(/Unknown option/);
  });
});

describe("Dokploy and Vardo calls", () => {
  it("sends the key as x-api-key and reads env", async () => {
    const f = vi.fn(async () => new Response(JSON.stringify({ env: "A=1" }), { status: 200 }));
    const text = await fetchDokployEnv("https://dok.example/", "fake-key", { kind: "compose", id: "c1" }, f as unknown as typeof fetch);
    expect(text).toBe("A=1");
    const [url, init] = f.mock.calls[0] as unknown as [string, RequestInit];
    expect(url).toBe("https://dok.example/api/compose.one?composeId=c1");
    expect((init.headers as Record<string, string>)["x-api-key"]).toBe("fake-key");
  });

  it("does not put the key or body in the error", async () => {
    const f = vi.fn(async () => new Response("secret body", { status: 401 }));
    const err = await fetchDokployEnv("https://dok.example", "fake-key", { kind: "application", id: "a" }, f as unknown as typeof fetch).catch((e) => e);
    expect(String(err.message)).toBe("Dokploy application.one failed: 401");
  });

  it("finds a Vardo app by exact name", async () => {
    const f = vi.fn(async () => new Response(JSON.stringify({ apps: [{ id: "1", name: "pouch-web" }, { id: "2", name: "pouch" }] }), { status: 200 }));
    expect(await findVardoApp("https://v.example", "k", "org", "pouch", f as unknown as typeof fetch)).toBe("2");
    await expect(findVardoApp("https://v.example", "k", "org", "nope", f as unknown as typeof fetch)).rejects.toThrow(/No Vardo app/);
  });
});
