import { describe, it, expect, vi } from "vitest";
import {
  parseDokployEnv,
  toVardoEnv,
  parseSource,
  parseArgs,
  fetchDokployEnv,
  findVardoApp,
} from "@/scripts/dokploy-env-import";
import { parseEnvContent } from "@/lib/env/parse-env-content";

// All values are fake.
const FIXTURE = [
  "# generated by Dokploy",
  "NODE_ENV=production",
  "DATABASE_URL=postgres://app:fake-pass@db:5432/app",
  'QUOTED="hello world"',
  "SINGLE='single value'",
  "export EXPORTED=yes",
  "HASH=abc#def",
  "HASH_SPACE=abc #comment",
  "ESCAPED=\"one\\ntwo\"",
  "LITERAL='one\\ntwo'",
  "dotted.name=x",
  "EMPTY=",
  "PADDED=\"  keep me  \"",
  'WRAPPED="\\"inner\\""',
  "SHARED=${{project.FAKE_SHARED}}",
  "DUP=first",
  "DUP=second",
  'PRIVATE_KEY="-----BEGIN FAKE-----',
  "line-two",
  '-----END FAKE-----"',
  "AFTER_MULTILINE=ok",
  "not a pair",
  "1BAD=x",
].join("\n");

describe("parseDokployEnv", () => {
  const map = new Map(parseDokployEnv(FIXTURE).map((e) => [e.key, e.value]));

  it("reads pairs the way Dokploy's dotenv does", () => {
    expect(map.get("NODE_ENV")).toBe("production");
    expect(map.get("QUOTED")).toBe("hello world");
    expect(map.get("SINGLE")).toBe("single value");
    expect(map.get("EXPORTED")).toBe("yes");
    expect(map.get("EMPTY")).toBe("");
    expect(map.get("PADDED")).toBe("  keep me  ");
  });

  it("ends an unquoted value at #, as dotenv does", () => {
    expect(map.get("HASH")).toBe("abc");
    expect(map.get("HASH_SPACE")).toBe("abc");
  });

  it("expands \\n only inside double quotes", () => {
    expect(map.get("ESCAPED")).toBe("one\ntwo");
    expect(map.get("LITERAL")).toBe("one\\ntwo");
  });

  it("joins multi-line quoted values and keeps parsing after them", () => {
    expect(map.get("PRIVATE_KEY")).toBe("-----BEGIN FAKE-----\nline-two\n-----END FAKE-----");
    expect(map.get("AFTER_MULTILINE")).toBe("ok");
  });

  it("drops comments and lines that aren't pairs", () => {
    expect([...map.keys()]).not.toContain("not a pair");
  });
});

describe("toVardoEnv", () => {
  const result = toVardoEnv(parseDokployEnv(FIXTURE));
  const back = new Map(parseEnvContent(result.content).map((e) => [e.key, e.value]));

  it("copies multi-line values", () => {
    expect(result.written).toContain("PRIVATE_KEY");
    expect(result.skipped).not.toContain("PRIVATE_KEY");
    expect(back.get("PRIVATE_KEY")).toBe("-----BEGIN FAKE-----\nline-two\n-----END FAKE-----");
    expect(back.get("AFTER_MULTILINE")).toBe("ok");
  });

  it("skips names Vardo can't use, by name", () => {
    expect(result.skipped.sort()).toEqual(["1BAD", "dotted.name"]);
    expect(result.content).not.toContain("dotted.name");
  });

  it("flags Dokploy shared-variable references", () => {
    expect(result.unresolved).toEqual(["SHARED"]);
  });

  it("keeps the last duplicate", () => {
    expect(result.content).toContain("DUP=second\n");
    expect(result.content).not.toContain("DUP=first");
  });

  it("round-trips every written value through Vardo's own env parser", () => {
    const dokploy = new Map(parseDokployEnv(FIXTURE).map((e) => [e.key, e.value]));
    for (const name of result.written) expect(back.get(name), name).toBe(dokploy.get(name));
    expect(back.get("PADDED")).toBe("  keep me  ");
    expect(back.get("WRAPPED")).toBe(dokploy.get("WRAPPED"));
    expect(back.get("EMPTY")).toBe("");
    expect(result.written).toHaveLength(back.size);
  });

  it("returns empty content for an empty env", () => {
    expect(toVardoEnv([]).content).toBe("");
  });
});

describe("toVardoEnv $$ handling", () => {
  const entries = parseDokployEnv(
    ["LOKI_PUSH_AUTH=user:$$2y$$10$$fakehash", "PLAIN=a$b", "PRICE=$$$$5", "NONE=x"].join("\n"),
  );

  it("turns $$ back into $ and names the keys it changed", () => {
    const r = toVardoEnv(entries);
    const back = new Map(parseEnvContent(r.content).map((e) => [e.key, e.value]));
    expect(back.get("LOKI_PUSH_AUTH")).toBe("user:$2y$10$fakehash");
    expect(back.get("PRICE")).toBe("$$5");
    expect(back.get("PLAIN")).toBe("a$b");
    expect(r.unescaped).toEqual(["LOKI_PUSH_AUTH", "PRICE"]);
  });

  it("keeps $$ with keepDollars", () => {
    const r = toVardoEnv(entries, { keepDollars: true });
    const back = new Map(parseEnvContent(r.content).map((e) => [e.key, e.value]));
    expect(back.get("LOKI_PUSH_AUTH")).toBe("user:$$2y$$10$$fakehash");
    expect(r.unescaped).toEqual([]);
  });

  it("parses --keep-dollars", () => {
    expect(parseArgs([]).keepDollars).toBe(false);
    expect(parseArgs(["--keep-dollars"]).keepDollars).toBe(true);
  });
});

describe("parseSource and parseArgs", () => {
  it("parses application and compose sources", () => {
    expect(parseSource("application:abc")).toEqual({ kind: "application", id: "abc" });
    expect(parseSource("compose:xyz")).toEqual({ kind: "compose", id: "xyz" });
    expect(() => parseSource("abc")).toThrow();
  });

  it("parses flags and rejects unknown ones", () => {
    const a = parseArgs(["--from", "compose:1", "--app", "pouch", "--dry-run"]);
    expect(a).toMatchObject({ from: "compose:1", app: "pouch", dryRun: true, overwrite: false });
    expect(() => parseArgs(["--api-key", "x"])).toThrow(/Unknown option/);
  });
});

describe("Dokploy and Vardo calls", () => {
  it("sends the key as x-api-key and reads env", async () => {
    const f = vi.fn(async () => new Response(JSON.stringify({ env: "A=1" }), { status: 200 }));
    const text = await fetchDokployEnv("https://dok.example/", "fake-key", { kind: "compose", id: "c1" }, f as unknown as typeof fetch);
    expect(text).toBe("A=1");
    const [url, init] = f.mock.calls[0] as unknown as [string, RequestInit];
    expect(url).toBe("https://dok.example/api/compose.one?composeId=c1");
    expect((init.headers as Record<string, string>)["x-api-key"]).toBe("fake-key");
  });

  it("does not put the key or body in the error", async () => {
    const f = vi.fn(async () => new Response("secret body", { status: 401 }));
    const err = await fetchDokployEnv("https://dok.example", "fake-key", { kind: "application", id: "a" }, f as unknown as typeof fetch).catch((e) => e);
    expect(String(err.message)).toBe("Dokploy application.one failed: 401");
  });

  it("finds a Vardo app by exact name", async () => {
    const f = vi.fn(async () => new Response(JSON.stringify({ apps: [{ id: "1", name: "pouch-web" }, { id: "2", name: "pouch" }] }), { status: 200 }));
    expect(await findVardoApp("https://v.example", "k", "org", "pouch", f as unknown as typeof fetch)).toBe("2");
    await expect(findVardoApp("https://v.example", "k", "org", "nope", f as unknown as typeof fetch)).rejects.toThrow(/No Vardo app/);
  });
});
