"use client";

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  CheckCircle,
  Download,
  Edit,
  Eye,
  Loader2,
  Mail,
  MoreHorizontal,
  Trash2,
} from "lucide-react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { format, parseISO } from "date-fns";

type Invoice = {
  id: string;
  invoiceNumber: string;
  status: string | null;
  isAutoGenerated: boolean | null;
  dueDate: string | null;
  periodStart: string;
  periodEnd: string;
  subtotal: number;
  totalMinutes: number;
  createdAt: string;
  sentAt: string | null;
  viewedAt: string | null;
  publicToken: string;
  client: {
    id: string;
    name: string;
    color: string | null;
  };
  lineItemCount: number;
};

type InvoiceListProps = {
  invoices: Invoice[];
  orgId: string;
  onRefresh: () => void;
};

function formatCurrency(cents: number): string {
  return `$${(cents / 100).toFixed(2)}`;
}

function formatHours(minutes: number): string {
  return (minutes / 60).toFixed(1);
}

function formatDateRange(start: string, end: string): string {
  const startDate = parseISO(start);
  const endDate = parseISO(end);
  return `${format(startDate, "MMM d")} - ${format(endDate, "MMM d, yyyy")}`;
}

function StatusBadge({ status, isAutoGenerated }: { status: string | null; isAutoGenerated: boolean | null }) {
  const styles: Record<string, string> = {
    in_progress: "bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300",
    draft: "bg-muted text-muted-foreground",
    sent: "bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-300",
    viewed: "bg-purple-100 text-purple-700 dark:bg-purple-950 dark:text-purple-300",
    paid: "bg-green-100 text-green-700 dark:bg-green-950 dark:text-green-300",
  };

  const labels: Record<string, string> = {
    in_progress: "In Progress",
    draft: "Draft",
    sent: "Sent",
    viewed: "Viewed",
    paid: "Paid",
  };

  // Auto-generated drafts show as "In Progress"
  const s = (status === "draft" && isAutoGenerated) ? "in_progress" : (status || "draft");
  return (
    <span
      className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${styles[s] || styles.draft}`}
    >
      {labels[s] || s}
    </span>
  );
}

export function InvoiceList({ invoices, orgId, onRefresh }: InvoiceListProps) {
  const router = useRouter();
  const [sendDialogOpen, setSendDialogOpen] = useState(false);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [selectedInvoice, setSelectedInvoice] = useState<Invoice | null>(null);
  const [sendEmail, setSendEmail] = useState("");
  const [sendMessage, setSendMessage] = useState("");
  const [isSending, setIsSending] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  const handleDownload = async (invoice: Invoice) => {
    setDownloadingId(invoice.id);
    try {
      const response = await fetch(
        `/api/v1/organizations/${orgId}/invoices/${invoice.id}/pdf`
      );
      if (!response.ok) throw new Error("Failed to download PDF");

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${invoice.invoiceNumber}-${invoice.client.name.replace(/[^a-zA-Z0-9]/g, "-")}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (err) {
      console.error("Download failed:", err);
    } finally {
      setDownloadingId(null);
    }
  };

  const handleOpenSendDialog = (invoice: Invoice) => {
    setSelectedInvoice(invoice);
    setSendEmail("");
    setSendMessage("");
    setSendDialogOpen(true);
  };

  const handleSend = async () => {
    if (!selectedInvoice || !sendEmail) return;

    setIsSending(true);
    try {
      const response = await fetch(
        `/api/v1/organizations/${orgId}/invoices/${selectedInvoice.id}/send`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            email: sendEmail,
            message: sendMessage || undefined,
          }),
        }
      );

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || "Failed to send invoice");
      }

      setSendDialogOpen(false);
      onRefresh();
    } catch (err) {
      console.error("Send failed:", err);
    } finally {
      setIsSending(false);
    }
  };

  const handleOpenDeleteDialog = (invoice: Invoice) => {
    setSelectedInvoice(invoice);
    setDeleteDialogOpen(true);
  };

  const handleDelete = async () => {
    if (!selectedInvoice) return;

    setIsDeleting(true);
    try {
      const response = await fetch(
        `/api/v1/organizations/${orgId}/invoices/${selectedInvoice.id}`,
        { method: "DELETE" }
      );

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || "Failed to delete invoice");
      }

      setDeleteDialogOpen(false);
      onRefresh();
    } catch (err) {
      console.error("Delete failed:", err);
    } finally {
      setIsDeleting(false);
    }
  };

  const handleMarkAsPaid = async (invoice: Invoice) => {
    try {
      const response = await fetch(
        `/api/v1/organizations/${orgId}/invoices/${invoice.id}`,
        {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ status: "paid" }),
        }
      );

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || "Failed to mark invoice as paid");
      }

      onRefresh();
    } catch (err) {
      console.error("Mark as paid failed:", err);
    }
  };

  if (invoices.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <p className="text-muted-foreground">No invoices yet.</p>
        <p className="text-sm text-muted-foreground">
          Generate your first invoice to get started.
        </p>
      </div>
    );
  }

  return (
    <>
      <div className="rounded-lg border">
        <table className="w-full">
          <thead>
            <tr className="border-b bg-muted/50">
              <th className="px-4 py-3 text-left text-sm font-medium text-muted-foreground">
                Invoice
              </th>
              <th className="px-4 py-3 text-left text-sm font-medium text-muted-foreground">
                Client
              </th>
              <th className="px-4 py-3 text-left text-sm font-medium text-muted-foreground">
                Period
              </th>
              <th className="px-4 py-3 text-left text-sm font-medium text-muted-foreground">
                Due Date
              </th>
              <th className="px-4 py-3 text-right text-sm font-medium text-muted-foreground">
                Hours
              </th>
              <th className="px-4 py-3 text-right text-sm font-medium text-muted-foreground">
                Amount
              </th>
              <th className="px-4 py-3 text-center text-sm font-medium text-muted-foreground">
                Status
              </th>
              <th className="px-4 py-3 text-right text-sm font-medium text-muted-foreground">
                Actions
              </th>
            </tr>
          </thead>
          <tbody>
            {invoices.map((invoice) => (
              <tr key={invoice.id} className="border-b last:border-0">
                <td className="px-4 py-3">
                  <Link
                    href={`/invoices/${invoice.id}/edit`}
                    className="font-medium text-primary hover:underline"
                  >
                    {invoice.invoiceNumber}
                  </Link>
                </td>
                <td className="px-4 py-3">
                  <div className="flex items-center gap-2">
                    {invoice.client.color && (
                      <div
                        className="size-2.5 rounded-full"
                        style={{ backgroundColor: invoice.client.color }}
                      />
                    )}
                    <span>{invoice.client.name}</span>
                  </div>
                </td>
                <td className="px-4 py-3 text-muted-foreground">
                  {formatDateRange(invoice.periodStart, invoice.periodEnd)}
                </td>
                <td className="px-4 py-3 text-muted-foreground">
                  {invoice.dueDate ? format(parseISO(invoice.dueDate), "MMM d, yyyy") : "—"}
                </td>
                <td className="px-4 py-3 text-right tabular-nums">
                  {formatHours(invoice.totalMinutes)}h
                </td>
                <td className="px-4 py-3 text-right font-medium tabular-nums">
                  {formatCurrency(invoice.subtotal)}
                </td>
                <td className="px-4 py-3 text-center">
                  <StatusBadge status={invoice.status} isAutoGenerated={invoice.isAutoGenerated} />
                </td>
                <td className="px-4 py-3 text-right">
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="size-8 squircle"
                      >
                        <MoreHorizontal className="size-4" />
                        <span className="sr-only">Open menu</span>
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end" className="squircle">
                      <DropdownMenuItem
                        onClick={() => handleDownload(invoice)}
                        disabled={downloadingId === invoice.id}
                      >
                        {downloadingId === invoice.id ? (
                          <Loader2 className="size-4 animate-spin" />
                        ) : (
                          <Download className="size-4" />
                        )}
                        Download PDF
                      </DropdownMenuItem>
                      <DropdownMenuItem
                        onClick={() =>
                          window.open(`/invoices/${invoice.publicToken}`, "_blank")
                        }
                      >
                        <Eye className="size-4" />
                        View
                      </DropdownMenuItem>
                      <DropdownMenuItem
                        onClick={() => router.push(`/invoices/${invoice.id}/edit`)}
                      >
                        <Edit className="size-4" />
                        Edit
                      </DropdownMenuItem>
                      <DropdownMenuItem
                        onClick={() => handleOpenSendDialog(invoice)}
                      >
                        <Mail className="size-4" />
                        Send via email
                      </DropdownMenuItem>
                      {invoice.status !== "paid" && (
                        <DropdownMenuItem
                          onClick={() => handleMarkAsPaid(invoice)}
                        >
                          <CheckCircle className="size-4" />
                          Mark as paid
                        </DropdownMenuItem>
                      )}
                      <DropdownMenuSeparator />
                      <DropdownMenuItem
                        className="text-destructive focus:text-destructive"
                        onClick={() => handleOpenDeleteDialog(invoice)}
                      >
                        <Trash2 className="size-4" />
                        Delete
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Send email dialog */}
      <Dialog open={sendDialogOpen} onOpenChange={setSendDialogOpen}>
        <DialogContent className="squircle sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Send Invoice</DialogTitle>
            <DialogDescription>
              Send {selectedInvoice?.invoiceNumber} to your client via email.
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid gap-2">
              <Label htmlFor="send-email">Recipient email</Label>
              <Input
                id="send-email"
                type="email"
                value={sendEmail}
                onChange={(e) => setSendEmail(e.target.value)}
                placeholder="client@example.com"
                className="squircle"
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="send-message">Message (optional)</Label>
              <textarea
                id="send-message"
                value={sendMessage}
                onChange={(e) => setSendMessage(e.target.value)}
                placeholder="Add a personal note..."
                rows={3}
                className="squircle flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
              />
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setSendDialogOpen(false)}
              disabled={isSending}
              className="squircle"
            >
              Cancel
            </Button>
            <Button
              onClick={handleSend}
              disabled={isSending || !sendEmail}
              className="squircle"
            >
              {isSending && <Loader2 className="size-4 animate-spin" />}
              Send Invoice
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete confirmation dialog */}
      <AlertDialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <AlertDialogContent className="squircle">
          <AlertDialogHeader>
            <AlertDialogTitle>Delete invoice?</AlertDialogTitle>
            <AlertDialogDescription>
              This will permanently delete invoice{" "}
              {selectedInvoice?.invoiceNumber}. This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel className="squircle" disabled={isDeleting}>
              Cancel
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDelete}
              disabled={isDeleting}
              className="squircle bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              {isDeleting && <Loader2 className="size-4 animate-spin" />}
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

    </>
  );
}
