"use client";

import { useState, useEffect, useMemo } from "react";
import {
  BottomSheet,
  BottomSheetContent,
  BottomSheetDescription,
  BottomSheetFooter,
  BottomSheetHeader,
  BottomSheetTitle,
} from "@/components/ui/bottom-sheet";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  Ban,
  CheckCircle,
  Download,
  Edit,
  Eye,
  Loader2,
  Mail,
  MoreHorizontal,
  Trash2,
} from "lucide-react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { format, parseISO } from "date-fns";
import { formatCurrency, formatHoursDecimal } from "@/lib/formatting";
import {
  ContactSuggestions,
  type SuggestableContact,
} from "@/components/contacts/contact-suggestions";
import { toast } from "sonner";

type Invoice = {
  id: string;
  invoiceNumber: string;
  status: string | null;
  isAutoGenerated: boolean | null;
  dueDate: string | null;
  periodStart: string;
  periodEnd: string;
  subtotal: number;
  totalMinutes: number;
  createdAt: string;
  sentAt: string | null;
  viewedAt: string | null;
  publicToken: string;
  client: {
    id: string;
    name: string;
    color: string | null;
  };
  lineItemCount: number;
  emailDeliveryStatus: string | null;
};

type InvoiceListProps = {
  invoices: Invoice[];
  orgId: string;
  onRefresh: () => void;
};

function formatHours(minutes: number): string {
  return formatHoursDecimal(minutes, 1);
}

function formatDateRange(start: string, end: string): string {
  const startDate = parseISO(start);
  const endDate = parseISO(end);
  return `${format(startDate, "MMM d")} - ${format(endDate, "MMM d, yyyy")}`;
}

const DELIVERY_LABELS: Record<string, string> = {
  delivered: "Delivered",
  bounced: "Bounced",
  complained: "Bounced",
  opened: "Opened",
  clicked: "Opened",
};

function StatusBadge({
  status,
  isAutoGenerated,
  emailDeliveryStatus,
}: {
  status: string | null;
  isAutoGenerated: boolean | null;
  emailDeliveryStatus?: string | null;
}) {
  const styles: Record<string, string> = {
    in_progress: "bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300",
    draft: "bg-muted text-muted-foreground",
    sent: "bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-300",
    viewed: "bg-purple-100 text-purple-700 dark:bg-purple-950 dark:text-purple-300",
    paid: "bg-green-100 text-green-700 dark:bg-green-950 dark:text-green-300",
    voided: "bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-300",
  };

  const labels: Record<string, string> = {
    in_progress: "In Progress",
    draft: "Draft",
    sent: "Sent",
    viewed: "Viewed",
    paid: "Paid",
    voided: "Voided",
  };

  // Auto-generated drafts show as "In Progress"
  const s = (status === "draft" && isAutoGenerated) ? "in_progress" : (status || "draft");
  const deliveryLabel = emailDeliveryStatus ? DELIVERY_LABELS[emailDeliveryStatus] : null;
  const isBounced = emailDeliveryStatus === "bounced" || emailDeliveryStatus === "complained";

  return (
    <span
      className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-medium ${
        isBounced
          ? "bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-300"
          : styles[s] || styles.draft
      }`}
    >
      {isBounced ? "Bounced" : labels[s] || s}
      {deliveryLabel && !isBounced && s === "sent" && (
        <span className="opacity-60">&middot; {deliveryLabel}</span>
      )}
    </span>
  );
}

export function InvoiceList({ invoices, orgId, onRefresh }: InvoiceListProps) {
  const router = useRouter();
  const [sendDialogOpen, setSendDialogOpen] = useState(false);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [bulkDeleteDialogOpen, setBulkDeleteDialogOpen] = useState(false);
  const [selectedInvoice, setSelectedInvoice] = useState<Invoice | null>(null);
  const [sendEmail, setSendEmail] = useState("");
  const [sendMessage, setSendMessage] = useState("");
  const [isSending, setIsSending] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [isBulkDeleting, setIsBulkDeleting] = useState(false);
  const [downloadingId, setDownloadingId] = useState<string | null>(null);
  const [sendContacts, setSendContacts] = useState<SuggestableContact[]>([]);
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());

  // Clear selection when invoices change
  useEffect(() => {
    setSelectedIds(new Set());
  }, [invoices]);

  // Fetch contacts when send dialog opens
  useEffect(() => {
    if (!sendDialogOpen || !selectedInvoice) {
      setSendContacts([]);
      return;
    }
    async function fetchContacts() {
      try {
        const res = await fetch(
          `/api/v1/organizations/${orgId}/clients/${selectedInvoice!.client.id}/contacts`
        );
        if (res.ok) {
          const data = await res.json();
          setSendContacts(data || []);
        }
      } catch {
        // Non-fatal — contacts are just suggestions
      }
    }
    fetchContacts();
  }, [sendDialogOpen, selectedInvoice, orgId]);

  // Draft invoices eligible for checkbox selection
  const draftIds = useMemo(
    () => new Set(invoices.filter((inv) => inv.status === "draft").map((inv) => inv.id)),
    [invoices]
  );

  const allDraftsSelected = draftIds.size > 0 && [...draftIds].every((id) => selectedIds.has(id));
  const someDraftsSelected = [...draftIds].some((id) => selectedIds.has(id));

  const toggleSelectAll = () => {
    if (allDraftsSelected) {
      setSelectedIds(new Set());
    } else {
      setSelectedIds(new Set(draftIds));
    }
  };

  const toggleSelect = (id: string) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  const handleDownload = async (invoice: Invoice) => {
    setDownloadingId(invoice.id);
    try {
      const response = await fetch(
        `/api/v1/organizations/${orgId}/invoices/${invoice.id}/pdf`
      );
      if (!response.ok) throw new Error("Failed to download PDF");

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${invoice.invoiceNumber}-${invoice.client.name.replace(/[^a-zA-Z0-9]/g, "-")}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (err) {
      console.error("Download failed:", err);
    } finally {
      setDownloadingId(null);
    }
  };

  const handleOpenSendDialog = (invoice: Invoice) => {
    setSelectedInvoice(invoice);
    setSendEmail("");
    setSendMessage("");
    setSendDialogOpen(true);
  };

  const handleSend = async () => {
    if (!selectedInvoice || !sendEmail) return;

    setIsSending(true);
    try {
      const response = await fetch(
        `/api/v1/organizations/${orgId}/invoices/${selectedInvoice.id}/send`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            email: sendEmail,
            message: sendMessage || undefined,
          }),
        }
      );

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || "Failed to send invoice");
      }

      setSendDialogOpen(false);
      onRefresh();
    } catch (err) {
      console.error("Send failed:", err);
    } finally {
      setIsSending(false);
    }
  };

  const handleOpenDeleteDialog = (invoice: Invoice) => {
    setSelectedInvoice(invoice);
    setDeleteDialogOpen(true);
  };

  const handleDelete = async () => {
    if (!selectedInvoice) return;

    setIsDeleting(true);
    try {
      const response = await fetch(
        `/api/v1/organizations/${orgId}/invoices/${selectedInvoice.id}`,
        { method: "DELETE" }
      );

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || "Failed to delete invoice");
      }

      const result = await response.json();
      setDeleteDialogOpen(false);
      toast.success(
        result.action === "voided" ? "Invoice voided" : "Invoice deleted"
      );
      onRefresh();
    } catch (err) {
      console.error("Delete failed:", err);
      toast.error("Failed to delete invoice");
    } finally {
      setIsDeleting(false);
    }
  };

  const handleBulkDelete = async () => {
    if (selectedIds.size === 0) return;

    setIsBulkDeleting(true);
    try {
      const response = await fetch(
        `/api/v1/organizations/${orgId}/invoices`,
        {
          method: "DELETE",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ invoiceIds: [...selectedIds] }),
        }
      );

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || "Failed to delete invoices");
      }

      const result = await response.json();
      setBulkDeleteDialogOpen(false);
      setSelectedIds(new Set());
      toast.success(`${result.deleted} draft${result.deleted !== 1 ? "s" : ""} deleted`);
      onRefresh();
    } catch (err) {
      console.error("Bulk delete failed:", err);
      toast.error("Failed to delete invoices");
    } finally {
      setIsBulkDeleting(false);
    }
  };

  const handleMarkAsPaid = async (invoice: Invoice) => {
    try {
      const response = await fetch(
        `/api/v1/organizations/${orgId}/invoices/${invoice.id}`,
        {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ status: "paid" }),
        }
      );

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || "Failed to mark invoice as paid");
      }

      onRefresh();
    } catch (err) {
      console.error("Mark as paid failed:", err);
    }
  };

  const isVoided = (invoice: Invoice) => invoice.status === "voided";

  if (invoices.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <p className="text-muted-foreground">No invoices yet.</p>
        <p className="text-sm text-muted-foreground">
          Generate your first invoice to get started.
        </p>
      </div>
    );
  }

  return (
    <>
      {/* Bulk action bar */}
      {selectedIds.size > 0 && (
        <div className="flex items-center gap-3 rounded-lg border bg-muted/50 px-4 py-2 mb-2">
          <span className="text-sm font-medium">
            {selectedIds.size} draft{selectedIds.size !== 1 ? "s" : ""} selected
          </span>
          <Button
            variant="destructive"
            size="sm"
            className="squircle"
            onClick={() => setBulkDeleteDialogOpen(true)}
          >
            <Trash2 className="size-4" />
            Delete {selectedIds.size} draft{selectedIds.size !== 1 ? "s" : ""}
          </Button>
          <Button
            variant="ghost"
            size="sm"
            className="squircle"
            onClick={() => setSelectedIds(new Set())}
          >
            Clear selection
          </Button>
        </div>
      )}

      <div className="rounded-lg border">
        <table className="w-full">
          <thead>
            <tr className="border-b bg-muted/50">
              <th className="px-4 py-3 text-left w-10">
                <Checkbox
                  checked={allDraftsSelected ? true : someDraftsSelected ? "indeterminate" : false}
                  onCheckedChange={toggleSelectAll}
                  disabled={draftIds.size === 0}
                  aria-label="Select all drafts"
                />
              </th>
              <th className="px-4 py-3 text-left text-sm font-medium text-muted-foreground">
                Invoice
              </th>
              <th className="px-4 py-3 text-left text-sm font-medium text-muted-foreground">
                Client
              </th>
              <th className="px-4 py-3 text-left text-sm font-medium text-muted-foreground">
                Period
              </th>
              <th className="px-4 py-3 text-left text-sm font-medium text-muted-foreground">
                Due Date
              </th>
              <th className="px-4 py-3 text-right text-sm font-medium text-muted-foreground">
                Hours
              </th>
              <th className="px-4 py-3 text-right text-sm font-medium text-muted-foreground">
                Amount
              </th>
              <th className="px-4 py-3 text-center text-sm font-medium text-muted-foreground">
                Status
              </th>
              <th className="px-4 py-3 text-right text-sm font-medium text-muted-foreground">
                Actions
              </th>
            </tr>
          </thead>
          <tbody>
            {invoices.map((invoice) => (
              <tr
                key={invoice.id}
                className={`border-b last:border-0 ${isVoided(invoice) ? "opacity-60" : ""}`}
              >
                <td className="px-4 py-3">
                  {invoice.status === "draft" ? (
                    <Checkbox
                      checked={selectedIds.has(invoice.id)}
                      onCheckedChange={() => toggleSelect(invoice.id)}
                      onClick={(e) => e.stopPropagation()}
                      aria-label={`Select ${invoice.invoiceNumber}`}
                    />
                  ) : (
                    <span className="block size-4" />
                  )}
                </td>
                <td className="px-4 py-3">
                  {isVoided(invoice) ? (
                    <span className="font-medium text-muted-foreground">
                      {invoice.invoiceNumber}
                    </span>
                  ) : (
                    <Link
                      href={`/invoices/${invoice.id}/edit`}
                      className="font-medium text-primary hover:underline"
                    >
                      {invoice.invoiceNumber}
                    </Link>
                  )}
                </td>
                <td className="px-4 py-3">
                  <div className="flex items-center gap-2">
                    {invoice.client.color && (
                      <div
                        className="size-2.5 rounded-full"
                        style={{ backgroundColor: invoice.client.color }}
                      />
                    )}
                    <span>{invoice.client.name}</span>
                  </div>
                </td>
                <td className="px-4 py-3 text-muted-foreground">
                  {formatDateRange(invoice.periodStart, invoice.periodEnd)}
                </td>
                <td className="px-4 py-3 text-muted-foreground">
                  {invoice.dueDate ? format(parseISO(invoice.dueDate), "MMM d, yyyy") : "—"}
                </td>
                <td className="px-4 py-3 text-right tabular-nums">
                  {formatHours(invoice.totalMinutes)}h
                </td>
                <td className="px-4 py-3 text-right font-medium tabular-nums">
                  {formatCurrency(invoice.subtotal)}
                </td>
                <td className="px-4 py-3 text-center">
                  <StatusBadge status={invoice.status} isAutoGenerated={invoice.isAutoGenerated} emailDeliveryStatus={invoice.emailDeliveryStatus} />
                </td>
                <td className="px-4 py-3 text-right">
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="size-8 squircle"
                      >
                        <MoreHorizontal className="size-4" />
                        <span className="sr-only">Open menu</span>
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end" className="squircle">
                      <DropdownMenuItem
                        onClick={() => handleDownload(invoice)}
                        disabled={downloadingId === invoice.id}
                      >
                        {downloadingId === invoice.id ? (
                          <Loader2 className="size-4 animate-spin" />
                        ) : (
                          <Download className="size-4" />
                        )}
                        Download PDF
                      </DropdownMenuItem>
                      <DropdownMenuItem
                        onClick={() =>
                          window.open(`/invoices/${invoice.publicToken}`, "_blank")
                        }
                      >
                        <Eye className="size-4" />
                        View
                      </DropdownMenuItem>
                      {!isVoided(invoice) && (
                        <>
                          <DropdownMenuItem
                            onClick={() => router.push(`/invoices/${invoice.id}/edit`)}
                          >
                            <Edit className="size-4" />
                            Edit
                          </DropdownMenuItem>
                          <DropdownMenuItem
                            onClick={() => handleOpenSendDialog(invoice)}
                          >
                            <Mail className="size-4" />
                            Send via email
                          </DropdownMenuItem>
                          {invoice.status !== "paid" && (
                            <DropdownMenuItem
                              onClick={() => handleMarkAsPaid(invoice)}
                            >
                              <CheckCircle className="size-4" />
                              Mark as paid
                            </DropdownMenuItem>
                          )}
                        </>
                      )}
                      {!isVoided(invoice) && (
                        <>
                          <DropdownMenuSeparator />
                          {invoice.status === "draft" ? (
                            <DropdownMenuItem
                              className="text-destructive focus:text-destructive"
                              onClick={() => handleOpenDeleteDialog(invoice)}
                            >
                              <Trash2 className="size-4" />
                              Delete
                            </DropdownMenuItem>
                          ) : (
                            <DropdownMenuItem
                              className="text-destructive focus:text-destructive"
                              onClick={() => handleOpenDeleteDialog(invoice)}
                            >
                              <Ban className="size-4" />
                              Void
                            </DropdownMenuItem>
                          )}
                        </>
                      )}
                    </DropdownMenuContent>
                  </DropdownMenu>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Send email dialog */}
      <BottomSheet open={sendDialogOpen} onOpenChange={setSendDialogOpen}>
        <BottomSheetContent className="squircle">
          <BottomSheetHeader>
            <BottomSheetTitle>Send Invoice</BottomSheetTitle>
            <BottomSheetDescription>
              Send {selectedInvoice?.invoiceNumber} to your client via email.
            </BottomSheetDescription>
          </BottomSheetHeader>
          <div className="flex-1 overflow-y-auto px-6 pb-6">
            <div className="grid gap-4">
              <div className="grid gap-2">
                <Label htmlFor="send-email">Recipient email</Label>
                <ContactSuggestions
                  contacts={sendContacts}
                  onSelect={(email) => setSendEmail(email)}
                />
                <Input
                  id="send-email"
                  type="email"
                  value={sendEmail}
                  onChange={(e) => setSendEmail(e.target.value)}
                  placeholder="client@example.com"
                  className="squircle"
                />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="send-message">Message (optional)</Label>
                <textarea
                  id="send-message"
                  value={sendMessage}
                  onChange={(e) => setSendMessage(e.target.value)}
                  placeholder="Add a personal note..."
                  rows={3}
                  className="squircle flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                />
              </div>
            </div>
          </div>
          <BottomSheetFooter>
            <Button
              variant="outline"
              onClick={() => setSendDialogOpen(false)}
              disabled={isSending}
              className="squircle"
            >
              Cancel
            </Button>
            <Button
              onClick={handleSend}
              disabled={isSending || !sendEmail}
              className="squircle"
            >
              {isSending && <Loader2 className="size-4 animate-spin" />}
              Send Invoice
            </Button>
          </BottomSheetFooter>
        </BottomSheetContent>
      </BottomSheet>

      {/* Delete/Void confirmation dialog */}
      <AlertDialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <AlertDialogContent className="squircle">
          <AlertDialogHeader>
            <AlertDialogTitle>
              {selectedInvoice?.status === "draft" ? "Delete invoice?" : "Void invoice?"}
            </AlertDialogTitle>
            <AlertDialogDescription>
              {selectedInvoice?.status === "draft"
                ? `This will permanently delete draft invoice ${selectedInvoice?.invoiceNumber}. This action cannot be undone.`
                : `This will void invoice ${selectedInvoice?.invoiceNumber}. The record will be preserved but marked as voided.`}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel className="squircle" disabled={isDeleting}>
              Cancel
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDelete}
              disabled={isDeleting}
              className="squircle bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              {isDeleting && <Loader2 className="size-4 animate-spin" />}
              {selectedInvoice?.status === "draft" ? "Delete" : "Void"}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Bulk delete confirmation dialog */}
      <AlertDialog open={bulkDeleteDialogOpen} onOpenChange={setBulkDeleteDialogOpen}>
        <AlertDialogContent className="squircle">
          <AlertDialogHeader>
            <AlertDialogTitle>Delete {selectedIds.size} draft{selectedIds.size !== 1 ? "s" : ""}?</AlertDialogTitle>
            <AlertDialogDescription>
              This will permanently delete {selectedIds.size} draft invoice{selectedIds.size !== 1 ? "s" : ""}. This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel className="squircle" disabled={isBulkDeleting}>
              Cancel
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={handleBulkDelete}
              disabled={isBulkDeleting}
              className="squircle bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              {isBulkDeleting && <Loader2 className="size-4 animate-spin" />}
              Delete {selectedIds.size} draft{selectedIds.size !== 1 ? "s" : ""}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}
