"use client";

import { useState, useEffect, useCallback, useMemo } from "react";
import { format, parseISO } from "date-fns";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { InvoiceDialog } from "@/components/invoices/invoice-dialog";
import { InvoiceList } from "@/components/invoices/invoice-list";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Plus, Loader2, X, RefreshCw, FileText } from "lucide-react";
import { cn } from "@/lib/utils";
import { ViewSwitcher } from "@/components/view-switcher";
import { useViewPreference } from "@/hooks/use-view-preference";
import { PageToolbar } from "@/components/page-toolbar";

type Invoice = {
  id: string;
  invoiceNumber: string;
  status: string | null;
  isAutoGenerated: boolean | null;
  dueDate: string | null;
  periodStart: string;
  periodEnd: string;
  subtotal: number;
  totalMinutes: number;
  createdAt: string;
  sentAt: string | null;
  viewedAt: string | null;
  publicToken: string;
  client: {
    id: string;
    name: string;
    color: string | null;
  };
  lineItemCount: number;
};

type Client = {
  id: string;
  name: string;
  color: string | null;
};

type InvoicesContentProps = {
  orgId: string;
};

const INVOICE_VIEWS = ["table", "list"] as const;

const INVOICE_STATUS_STYLES: Record<string, string> = {
  in_progress: "bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300",
  draft: "bg-muted text-muted-foreground",
  sent: "bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-300",
  viewed: "bg-purple-100 text-purple-700 dark:bg-purple-950 dark:text-purple-300",
  paid: "bg-green-100 text-green-700 dark:bg-green-950 dark:text-green-300",
};

const INVOICE_STATUS_LABELS: Record<string, string> = {
  in_progress: "In Progress",
  draft: "Draft",
  sent: "Sent",
  viewed: "Viewed",
  paid: "Paid",
};

function formatCurrency(cents: number): string {
  return `$${(cents / 100).toFixed(2)}`;
}

function formatHours(minutes: number): string {
  return (minutes / 60).toFixed(1);
}

export function InvoicesContent({ orgId }: InvoicesContentProps) {
  const [view, setView] = useViewPreference("invoices", INVOICE_VIEWS, "table");
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [clients, setClients] = useState<Client[]>([]);
  const [aiSummaryAvailable, setAiSummaryAvailable] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [isRefreshing, setIsRefreshing] = useState(false);

  // Filters
  const [clientFilter, setClientFilter] = useState<string>("all");
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [dateFrom, setDateFrom] = useState<string>("");
  const [dateTo, setDateTo] = useState<string>("");

  const fetchInvoices = useCallback(async () => {
    setIsLoading(true);
    try {
      const response = await fetch(`/api/v1/organizations/${orgId}/invoices`);
      if (!response.ok) throw new Error("Failed to fetch invoices");
      const data = await response.json();
      setInvoices(data.invoices);
      setAiSummaryAvailable(data.aiSummaryAvailable || false);
    } catch (err) {
      console.error("Error fetching invoices:", err);
    } finally {
      setIsLoading(false);
    }
  }, [orgId]);

  const fetchClients = useCallback(async () => {
    try {
      const response = await fetch(`/api/v1/organizations/${orgId}/clients`);
      if (!response.ok) throw new Error("Failed to fetch clients");
      const data = await response.json();
      setClients(data.clients || []);
    } catch (err) {
      console.error("Error fetching clients:", err);
    }
  }, [orgId]);

  useEffect(() => {
    fetchInvoices();
    fetchClients();
  }, [fetchInvoices, fetchClients]);

  const handleSuccess = () => {
    fetchInvoices();
  };

  const handleRefresh = async () => {
    setIsRefreshing(true);
    await fetchInvoices();
    setIsRefreshing(false);
  };

  const clearFilters = () => {
    setClientFilter("all");
    setStatusFilter("all");
    setDateFrom("");
    setDateTo("");
  };

  const hasActiveFilters = clientFilter !== "all" || statusFilter !== "all" || dateFrom || dateTo;

  // Apply filters
  const filteredInvoices = useMemo(() => {
    return invoices.filter((invoice) => {
      // Client filter
      if (clientFilter !== "all" && invoice.client.id !== clientFilter) {
        return false;
      }

      // Status filter (handle "in_progress" as auto-generated drafts)
      if (statusFilter !== "all") {
        if (statusFilter === "in_progress") {
          if (!(invoice.status === "draft" && invoice.isAutoGenerated)) {
            return false;
          }
        } else if (statusFilter === "draft") {
          // Regular drafts only (not auto-generated)
          if (!(invoice.status === "draft" && !invoice.isAutoGenerated)) {
            return false;
          }
        } else if (statusFilter === "paid") {
          if (invoice.status !== "paid") {
            return false;
          }
        } else if (invoice.status !== statusFilter) {
          return false;
        }
      }

      // Date range filter (based on period)
      if (dateFrom && invoice.periodEnd < dateFrom) {
        return false;
      }
      if (dateTo && invoice.periodStart > dateTo) {
        return false;
      }

      return true;
    });
  }, [invoices, clientFilter, statusFilter, dateFrom, dateTo]);

  return (
    <div className="space-y-4">
      <PageToolbar
        actions={
          <>
            <Button
              variant="outline"
              onClick={handleRefresh}
              disabled={isRefreshing}
              className="squircle"
            >
              <RefreshCw className={`size-4 ${isRefreshing ? "animate-spin" : ""}`} />
              Refresh
            </Button>
            <ViewSwitcher views={INVOICE_VIEWS} value={view} onValueChange={setView} />
            <Button onClick={() => setDialogOpen(true)} className="squircle">
              <Plus className="size-4" />
              New Invoice
            </Button>
          </>
        }
      >
        <Select value={clientFilter} onValueChange={setClientFilter}>
          <SelectTrigger className="squircle w-[180px]">
            <SelectValue placeholder="All clients" />
          </SelectTrigger>
          <SelectContent className="squircle">
            <SelectItem value="all">All clients</SelectItem>
            {clients.map((client) => (
              <SelectItem key={client.id} value={client.id}>
                <span className="flex items-center gap-2">
                  {client.color && (
                    <span
                      className="size-2 rounded-full shrink-0"
                      style={{ backgroundColor: client.color }}
                    />
                  )}
                  {client.name}
                </span>
              </SelectItem>
            ))}
          </SelectContent>
        </Select>

        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="squircle w-[150px]">
            <SelectValue placeholder="All statuses" />
          </SelectTrigger>
          <SelectContent className="squircle">
            <SelectItem value="all">All statuses</SelectItem>
            <SelectItem value="in_progress">In Progress</SelectItem>
            <SelectItem value="draft">Draft</SelectItem>
            <SelectItem value="sent">Sent</SelectItem>
            <SelectItem value="viewed">Viewed</SelectItem>
            <SelectItem value="paid">Paid</SelectItem>
          </SelectContent>
        </Select>

        <Input
          type="date"
          value={dateFrom}
          onChange={(e) => setDateFrom(e.target.value)}
          placeholder="From"
          className="squircle w-[140px]"
        />

        <Input
          type="date"
          value={dateTo}
          onChange={(e) => setDateTo(e.target.value)}
          placeholder="To"
          className="squircle w-[140px]"
        />

        {hasActiveFilters && (
          <Button
            variant="ghost"
            size="icon"
            onClick={clearFilters}
            title="Clear filters"
          >
            <X className="size-4" />
          </Button>
        )}
      </PageToolbar>

      {/* Results count */}
      {hasActiveFilters && (
        <p className="text-sm text-muted-foreground">
          Showing {filteredInvoices.length} of {invoices.length} invoices
        </p>
      )}

      {isLoading ? (
        <div className="flex items-center justify-center py-12">
          <Loader2 className="size-6 animate-spin text-muted-foreground" />
        </div>
      ) : filteredInvoices.length === 0 ? (
        <Card className="squircle">
          <CardContent className="py-12 text-center">
            <div className="mx-auto flex size-12 items-center justify-center rounded-full bg-muted">
              <FileText className="size-6 text-muted-foreground" />
            </div>
            <h3 className="mt-4 text-lg font-medium">No invoices yet</h3>
            <p className="mt-2 text-sm text-muted-foreground">
              Generate your first invoice to get started.
            </p>
            <Button onClick={() => setDialogOpen(true)} className="mt-4 squircle">
              <Plus className="size-4" />
              New Invoice
            </Button>
          </CardContent>
        </Card>
      ) : view === "table" ? (
        <InvoiceList
          invoices={filteredInvoices}
          orgId={orgId}
          onRefresh={fetchInvoices}
        />
      ) : (
        <div className="space-y-2">
          {filteredInvoices.map((invoice) => {
            const status = (invoice.status === "draft" && invoice.isAutoGenerated)
              ? "in_progress"
              : (invoice.status || "draft");

            return (
              <Card
                key={invoice.id}
                className="squircle hover:bg-accent/50 transition-colors cursor-pointer"
                onClick={() => window.location.href = `/invoices/${invoice.id}/edit`}
              >
                <CardContent className="p-4">
                  <div className="flex items-center justify-between gap-4">
                    <div className="flex items-center gap-4 min-w-0">
                      <div
                        className="size-3 rounded-full shrink-0"
                        style={{ backgroundColor: invoice.client.color || "#94a3b8" }}
                      />
                      <div className="min-w-0">
                        <div className="flex items-center gap-2">
                          <span className="font-medium">{invoice.invoiceNumber}</span>
                          <span className="text-muted-foreground">{invoice.client.name}</span>
                          <span
                            className={cn(
                              "inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium",
                              INVOICE_STATUS_STYLES[status] || INVOICE_STATUS_STYLES.draft
                            )}
                          >
                            {INVOICE_STATUS_LABELS[status] || status}
                          </span>
                        </div>
                        <div className="flex items-center gap-2 text-sm text-muted-foreground mt-0.5">
                          <span>
                            {format(parseISO(invoice.periodStart), "MMM d")} – {format(parseISO(invoice.periodEnd), "MMM d, yyyy")}
                          </span>
                          <span>&middot;</span>
                          <span>{formatHours(invoice.totalMinutes)}h</span>
                          {invoice.dueDate && (
                            <>
                              <span>&middot;</span>
                              <span>Due {format(parseISO(invoice.dueDate), "MMM d")}</span>
                            </>
                          )}
                        </div>
                      </div>
                    </div>
                    <div className="text-right shrink-0">
                      <span className="font-medium tabular-nums">
                        {formatCurrency(invoice.subtotal)}
                      </span>
                    </div>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}

      <InvoiceDialog
        open={dialogOpen}
        onOpenChange={setDialogOpen}
        orgId={orgId}
        onSuccess={handleSuccess}
        aiSummaryAvailable={aiSummaryAvailable}
      />
    </div>
  );
}
