"use client";

import { useState, useEffect, useCallback, useMemo } from "react";
import { Button } from "@/components/ui/button";
import { InvoiceDialog } from "@/components/invoices/invoice-dialog";
import { InvoiceList } from "@/components/invoices/invoice-list";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Plus, Loader2, X, RefreshCw } from "lucide-react";

type Invoice = {
  id: string;
  invoiceNumber: string;
  status: string | null;
  isAutoGenerated: boolean | null;
  dueDate: string | null;
  periodStart: string;
  periodEnd: string;
  subtotal: number;
  totalMinutes: number;
  createdAt: string;
  sentAt: string | null;
  viewedAt: string | null;
  publicToken: string;
  client: {
    id: string;
    name: string;
    color: string | null;
  };
  lineItemCount: number;
};

type Client = {
  id: string;
  name: string;
  color: string | null;
};

type InvoicesContentProps = {
  orgId: string;
};

export function InvoicesContent({ orgId }: InvoicesContentProps) {
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [clients, setClients] = useState<Client[]>([]);
  const [aiSummaryAvailable, setAiSummaryAvailable] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [isRefreshing, setIsRefreshing] = useState(false);

  // Filters
  const [clientFilter, setClientFilter] = useState<string>("all");
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [dateFrom, setDateFrom] = useState<string>("");
  const [dateTo, setDateTo] = useState<string>("");

  const fetchInvoices = useCallback(async () => {
    setIsLoading(true);
    try {
      const response = await fetch(`/api/v1/organizations/${orgId}/invoices`);
      if (!response.ok) throw new Error("Failed to fetch invoices");
      const data = await response.json();
      setInvoices(data.invoices);
      setAiSummaryAvailable(data.aiSummaryAvailable || false);
    } catch (err) {
      console.error("Error fetching invoices:", err);
    } finally {
      setIsLoading(false);
    }
  }, [orgId]);

  const fetchClients = useCallback(async () => {
    try {
      const response = await fetch(`/api/v1/organizations/${orgId}/clients`);
      if (!response.ok) throw new Error("Failed to fetch clients");
      const data = await response.json();
      setClients(data.clients || []);
    } catch (err) {
      console.error("Error fetching clients:", err);
    }
  }, [orgId]);

  useEffect(() => {
    fetchInvoices();
    fetchClients();
  }, [fetchInvoices, fetchClients]);

  const handleSuccess = () => {
    fetchInvoices();
  };

  const handleRefresh = async () => {
    setIsRefreshing(true);
    await fetchInvoices();
    setIsRefreshing(false);
  };

  const clearFilters = () => {
    setClientFilter("all");
    setStatusFilter("all");
    setDateFrom("");
    setDateTo("");
  };

  const hasActiveFilters = clientFilter !== "all" || statusFilter !== "all" || dateFrom || dateTo;

  // Apply filters
  const filteredInvoices = useMemo(() => {
    return invoices.filter((invoice) => {
      // Client filter
      if (clientFilter !== "all" && invoice.client.id !== clientFilter) {
        return false;
      }

      // Status filter (handle "in_progress" as auto-generated drafts)
      if (statusFilter !== "all") {
        if (statusFilter === "in_progress") {
          if (!(invoice.status === "draft" && invoice.isAutoGenerated)) {
            return false;
          }
        } else if (statusFilter === "draft") {
          // Regular drafts only (not auto-generated)
          if (!(invoice.status === "draft" && !invoice.isAutoGenerated)) {
            return false;
          }
        } else if (statusFilter === "paid") {
          if (invoice.status !== "paid") {
            return false;
          }
        } else if (invoice.status !== statusFilter) {
          return false;
        }
      }

      // Date range filter (based on period)
      if (dateFrom && invoice.periodEnd < dateFrom) {
        return false;
      }
      if (dateTo && invoice.periodStart > dateTo) {
        return false;
      }

      return true;
    });
  }, [invoices, clientFilter, statusFilter, dateFrom, dateTo]);

  return (
    <div className="space-y-4">
      {/* Filters */}
      <div className="flex flex-wrap items-end gap-3">
        <div className="flex-1 min-w-[150px] max-w-[200px]">
          <Label htmlFor="client-filter" className="text-xs text-muted-foreground mb-1 block">
            Client
          </Label>
          <Select value={clientFilter} onValueChange={setClientFilter}>
            <SelectTrigger id="client-filter" className="squircle h-9">
              <SelectValue placeholder="All clients" />
            </SelectTrigger>
            <SelectContent className="squircle">
              <SelectItem value="all">All clients</SelectItem>
              {clients.map((client) => (
                <SelectItem key={client.id} value={client.id}>
                  <span className="flex items-center gap-2">
                    {client.color && (
                      <span
                        className="size-2 rounded-full shrink-0"
                        style={{ backgroundColor: client.color }}
                      />
                    )}
                    {client.name}
                  </span>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="min-w-[140px]">
          <Label htmlFor="status-filter" className="text-xs text-muted-foreground mb-1 block">
            Status
          </Label>
          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger id="status-filter" className="squircle h-9">
              <SelectValue placeholder="All statuses" />
            </SelectTrigger>
            <SelectContent className="squircle">
              <SelectItem value="all">All statuses</SelectItem>
              <SelectItem value="in_progress">In Progress</SelectItem>
              <SelectItem value="draft">Draft</SelectItem>
              <SelectItem value="sent">Sent</SelectItem>
              <SelectItem value="viewed">Viewed</SelectItem>
              <SelectItem value="paid">Paid</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <div className="min-w-[130px]">
          <Label htmlFor="date-from" className="text-xs text-muted-foreground mb-1 block">
            From
          </Label>
          <Input
            id="date-from"
            type="date"
            value={dateFrom}
            onChange={(e) => setDateFrom(e.target.value)}
            className="squircle h-9"
          />
        </div>

        <div className="min-w-[130px]">
          <Label htmlFor="date-to" className="text-xs text-muted-foreground mb-1 block">
            To
          </Label>
          <Input
            id="date-to"
            type="date"
            value={dateTo}
            onChange={(e) => setDateTo(e.target.value)}
            className="squircle h-9"
          />
        </div>

        {hasActiveFilters && (
          <Button
            variant="ghost"
            size="sm"
            onClick={clearFilters}
            className="h-9 px-2 text-muted-foreground"
          >
            <X className="size-4 mr-1" />
            Clear
          </Button>
        )}

        <div className="flex-1" />

        <Button
          variant="outline"
          onClick={handleRefresh}
          disabled={isRefreshing}
          className="squircle h-9"
        >
          <RefreshCw className={`size-4 ${isRefreshing ? "animate-spin" : ""}`} />
          Refresh
        </Button>

        <Button onClick={() => setDialogOpen(true)} className="squircle h-9">
          <Plus className="size-4" />
          New Invoice
        </Button>
      </div>

      {/* Results count */}
      {hasActiveFilters && (
        <p className="text-sm text-muted-foreground">
          Showing {filteredInvoices.length} of {invoices.length} invoices
        </p>
      )}

      {isLoading ? (
        <div className="flex items-center justify-center py-12">
          <Loader2 className="size-6 animate-spin text-muted-foreground" />
        </div>
      ) : (
        <InvoiceList
          invoices={filteredInvoices}
          orgId={orgId}
          onRefresh={fetchInvoices}
        />
      )}

      <InvoiceDialog
        open={dialogOpen}
        onOpenChange={setDialogOpen}
        orgId={orgId}
        onSuccess={handleSuccess}
        aiSummaryAvailable={aiSummaryAvailable}
      />
    </div>
  );
}
